#!/usr/bin/env ruby
message_file = ARGV[0]
message = File.read(message_file)

# sloppy i know, but at least we have some guards
$regex = /^((feat|tests?|lint|refactor|ci|git|special|doc|typo|log|ts|fix|wip)(-fix|-fail)?(, ?)?)+: .+/

if !$regex.match(message)
  puts "[POLICY] Your message is not formatted correctly. Respect the regex: '#{$regex}'!"
  exit 1
end
