#!/bin/sh

set -eu

if ! [ -x "$(command -v npm)" ]; then
  echo 'Error: npm not found. Make it available to the host shell (e.g., with "nvm use --lts").'
  exit 2
fi


reset() {
  echo "Cleaning up and return control"
  rm -r "$flowrtmpdir"
  cd "$curdir"
}

unclean=false
if [ -n "$(git status --porcelain)" ]; then
  # if we directly assign the test set -eu will not approve
  unclean=true
  echo "Working tree is not clean, so we reset in temporary folder"
  # backwards compatible platform independence
  flowrtmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'flowrtmpdir')
  echo "Using temporary folder $flowrtmpdir"

  curdir=$(pwd)

  cp -r . "$flowrtmpdir"
  cd "$flowrtmpdir"

  git stash save --keep-index --include-untracked
  trap reset EXIT
fi

echo "Linting project (local mode)..."
npm run lint-local

lfspre() {
  if $unclean; then
    reset
  fi
  command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
  git lfs pre-push "$@"
}

# we register it as a trap after lint so that it 1) triggers only if lint-local succeeded
# but 2) only triggers *after* the directory recovery completed
trap lfspre EXIT
