#!/bin/sh

# run linter

if ! [ -x "$(command -v npm)" ]; then
  # first, try to setup with nvm
  if ! [ -x "$(command -v nvm)" ]; then
    echo 'Error: neither npm nor nvm found.' >&2
  fi
  nvm use --lts
fi

echo "Linting project"
npm run lint > /dev/null && echo "Linting passed"


command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
git lfs pre-push "$@"
