import type { FunctionInfo } from './function-info';
import { SemanticCallTag } from '../../../../dataflow/environments/built-in-props';
import { functionInfosFromProps } from './derived-functions';
import { OtherPathFunctions } from './other-path-functions';
import { PkgName } from '../../../../dataflow/environments/identifier';

const ReadFunctionsWithMore: FunctionInfo[] = [
	{ package: 'base', name: 'parse',                          argName: 'file', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'utils', name: 'read.table',         argIdx: 0, argName: 'file', resolveValue: true, ignoreIf: 'arg-set', additionalArgs: { argSet: { argName: 'text' } } },
	{ package: 'utils', name: 'read.csv',           argIdx: 0, argName: 'file', resolveValue: true, ignoreIf: 'arg-set', additionalArgs: { argSet: { argName: 'text' } } },
	{ package: 'utils', name: 'read.csv2',          argIdx: 0, argName: 'file', resolveValue: true, ignoreIf: 'arg-set', additionalArgs: { argSet: { argName: 'text' } } },
	{ package: 'utils', name: 'read.delim',         argIdx: 0, argName: 'file', resolveValue: true, ignoreIf: 'arg-set', additionalArgs: { argSet: { argName: 'text' } } },
	{ package: 'utils', name: 'read.delim2',        argIdx: 0, argName: 'file', resolveValue: true, ignoreIf: 'arg-set', additionalArgs: { argSet: { argName: 'text' } } },
	{ package: 'base', name: 'read.dcf',            argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'utils', name: 'read.fwf',            argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'base', name: 'file',                argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'base', name: 'url',                 argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'base', name: 'gzfile',              argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'base', name: 'bzfile',              argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'utils', name: 'download.file',       argIdx: 0, argName: 'url',  resolveValue: true },
	{ package: 'base', name: 'pipe',                argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'base', name: 'fifo',                argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'base', name: 'unz',                 argIdx: 0, argName: 'description', resolveValue: true, ignoreIf: 'mode-only-write', additionalArgs: { mode: { argIdx: 1, argName: 'open', resolveValue: true } } },
	{ package: 'base', name: 'matrix',              argIdx: 0, argName: 'data', resolveValue: true },
	/* `data(mtcars)` names the dataset as a symbol (or as a string with `character.only`), just like `library` */
	{ package: 'utils', name: 'data',               argIdx: 0, resolveValue: 'library', ignoreIf: 'arg-missing' },
	{ package: 'base', name: 'readRenviron',        argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'readr', name: 'read_csv',           argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_csv2',          argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_lines',         argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_delim',         argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_fwf',           argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_tsv',           argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_table',         argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_log',           argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_lines_raw',     argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_lines_chunked', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'read_rds',           argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readr', name: 'clipboard'                                                          },
	{ package: 'xlsx', name: 'read.xlsx',           argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'xlsx', name: 'read.xlsx2',          argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'data.table', name: 'fread', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'haven', name: 'read_sas', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'haven', name: 'read_sav', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'haven', name: 'read_por', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'haven', name: 'read_dta', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'haven', name: 'read_xpt', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'feather', name: 'read_feather', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.arff',    argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.dbf',     argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.dta',     argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.epiinfo', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.mtp',     argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.octave',  argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.spss',    argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.ssd',     argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.systat',  argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'foreign', name: 'read.xport',   argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'car', name: 'Import', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'magick', name: 'image_read',       argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'magick', name: 'image_read_svg',   argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'magick', name: 'image_read_pdf',   argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'magick', name: 'image_read_video', argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'LIM', name: 'Read', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'sourcetools', name: 'read',             argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'sourcetools', name: 'read_lines',       argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'sourcetools', name: 'read_bytes',       argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'sourcetools', name: 'read_lines_bytes', argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'sourcetools', name: 'tokenize',                    argName: 'file', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'sourcetools', name: 'tokenize_file',    argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'expss', name: 'read_spss',         argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'SimPhe', name: 'read.geno', argIdx: 0, argName: 'fname', resolveValue: true },
	{ package: 'ape', name: 'read.tree', argName: 'file', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'geomorph', name: 'readland.tps', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readxl', name: 'read_excel', argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'readxl', name: 'read_xls',   argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'readxl', name: 'read_xlsx',  argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'sf', name: 'read_sf', argIdx: 0, argName: 'dsn', resolveValue: true },
	{ package: 'sf', name: 'st_read', argIdx: 0, argName: 'dsn', resolveValue: true },
	{ package: 'rgdal', name: 'readOGR',       argIdx: 0, argName: 'dsn',   resolveValue: true },
	{ package: 'rgdal', name: 'ogrInfo',       argIdx: 0, argName: 'dsn',   resolveValue: true },
	{ package: 'rgdal', name: 'ogrFIDs',       argIdx: 0, argName: 'dsn',   resolveValue: true },
	{ package: 'rgdal', name: 'OGRSpatialRef', argIdx: 0, argName: 'dsn',   resolveValue: true },
	{ package: 'rgdal', name: 'ogrListLayers', argIdx: 0, argName: 'dsn',   resolveValue: true },
	{ package: 'rgdal', name: 'readGDAL',      argIdx: 0, argName: 'fname', resolveValue: true },
	{ package: 'readstata13', name: 'read.dta13', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'arrow', name: 'read_parquet', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'maptools', name: 'readShapePoly', argIdx: 0, argName: 'fn', resolveValue: true },
	{ package: 'XLConnect', name: 'readWorksheetFromFile',   argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'XLConnect', name: 'readNamedRegionFromFile', argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'XLConnect', name: 'loadWorkbook',            argIdx: 0, argName: 'filename', resolveValue: true },
	{ package: 'DiagrammeR', name: 'import_graph', argIdx: 0, argName: 'graph_file', resolveValue: true },
	{ package: 'DiagrammeR', name: 'open_graph',   argIdx: 0, argName: 'file',       resolveValue: true },
	{ package: 'highcharter', name: 'download_map_data', argIdx: 0, argName: 'url', resolveValue: true, defaultValue: 'custom/world.js' },
	{ name: 'read_html',                       argIdx: 0, argName: 'x',   resolveValue: true },
	{ package: 'rvest', name: 'read_html_live', argIdx: 0, argName: 'url', resolveValue: true },
	{ package: 'stats', name: 'read.ftable',    argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'DBI', name: 'dbReadTable',      argIdx: 1, argName: 'name', resolveValue: true },
	{ package: 'DBI', name: 'dbReadTableArrow', argIdx: 1, argName: 'name', resolveValue: true },
	{ package: PkgName.Jsonlite, name: 'read_json', argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'rpolars', name: 'pl_read_ipc', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_read_csv', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_read_ndjson', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_read_parquet', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_scan_csv', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_scan_ipc', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_scan_ndjson', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rpolars', name: 'pl_scan_parquet', argIdx: 0, argName: 'source', resolveValue: true, ignoreIf: 'arg-missing' },
	{ package: 'rio', name: 'import', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'rio', name: 'import_list', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'openxlsx', name: 'read.xlsx', argIdx: 0, argName: 'xlsxFile', resolveValue: true },
	{ package: 'openxlsx', name: 'loadWorkbook', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'readODS', name: 'read_ods', argIdx: 0, argName: 'path', resolveValue: true },
	{ package: 'vroom', name: 'vroom', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'compiler', name: 'loadcmp', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'compiler', name: 'cmpfile', argIdx: 0, argName: 'infile', resolveValue: true },
	/* image / raster */
	{ package: 'jpeg',       name: 'readJPEG',       argIdx: 0, argName: 'source',   resolveValue: true },
	{ package: 'png',        name: 'readPNG',         argIdx: 0, argName: 'source',   resolveValue: true },
	{ package: 'tiff',       name: 'readTIFF',        argIdx: 0, argName: 'source',   resolveValue: true },
	{ package: 'imager',     name: 'load.image',      argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'imager',     name: 'load.video',      argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'imager',     name: 'load.dir',        argIdx: 0, argName: 'path',     resolveValue: true },
	{ package: 'OpenImageR', name: 'readImage',       argIdx: 0, argName: 'path',     resolveValue: true },
	{ package: 'EBImage',    name: 'readImage',       argIdx: 0, argName: 'files',    resolveValue: true },
	/* audio / video */
	{ package: 'av',     name: 'av_video_images', argIdx: 0, argName: 'video', resolveValue: true },
	{ package: 'av',     name: 'read_audio_bin',  argIdx: 0, argName: 'audio', resolveValue: true },
	{ package: 'av',     name: 'read_audio_fft',  argIdx: 0, argName: 'audio', resolveValue: true },
	{ package: 'tuneR',  name: 'readWave',         argIdx: 0, argName: 'filename', resolveValue: true },
	{ package: 'tuneR',  name: 'readMP3',          argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'tuneR',  name: 'readMidi',         argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'seewave', name: 'read.audacity',   argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'audio',  name: 'load.wave',         argIdx: 0, argName: 'where',   resolveValue: true },
	/* geospatial (no `raster::stack`: only the name is matched on and `utils::stack` shares it) */
	{ package: 'terra',    name: 'rast',            argIdx: 0, argName: 'x',   resolveValue: true },
	{ package: 'terra',    name: 'vect',            argIdx: 0, argName: 'x',   resolveValue: true },
	{ package: 'raster',   name: 'raster',          argIdx: 0, argName: 'x',   resolveValue: true },
	{ package: 'raster',   name: 'brick',           argIdx: 0, argName: 'x',   resolveValue: true },
	{ package: 'raster',   name: 'shapefile',       argIdx: 0, argName: 'x',   resolveValue: true },
	{ package: 'stars',    name: 'read_stars',      argIdx: 0, argName: '.x',  resolveValue: true },
	{ package: 'stars',    name: 'read_ncdf',       argIdx: 0, argName: '.x',  resolveValue: true },
	{ package: 'maptools', name: 'readShapeLines',   argIdx: 0, argName: 'fn', resolveValue: true },
	{ package: 'maptools', name: 'readShapePoints',  argIdx: 0, argName: 'fn', resolveValue: true },
	{ package: 'maptools', name: 'readShapeSpatial', argIdx: 0, argName: 'fn', resolveValue: true },
	/* array / binary science formats */
	{ package: 'ncdf4',    name: 'nc_open',   argIdx: 0, argName: 'filename', resolveValue: true },
	{ package: 'RNetCDF',  name: 'open.nc',   argIdx: 0, argName: 'con',      resolveValue: true },
	{ package: 'R.matlab', name: 'readMat',   argIdx: 0, argName: 'con',      resolveValue: true },
	{ package: 'rhdf5',    name: 'h5read',    argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'rhdf5',    name: 'h5ls',      argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'fst',      name: 'read_fst',  argIdx: 0, argName: 'path',     resolveValue: true },
	{ package: 'qs',       name: 'qread',     argIdx: 0, argName: 'file',     resolveValue: true },
	{ package: 'yaml',     name: 'read_yaml', argIdx: 0, argName: 'file',     resolveValue: true, ignoreIf: 'arg-set', additionalArgs: { argSet: { argName: 'text' } } },
	/* phylogeny / sequence */
	{ package: 'ape',    name: 'read.nexus',      argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'ape',    name: 'read.nexus.data', argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'ape',    name: 'read.dna',        argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'ape',    name: 'read.FASTA',      argIdx: 0, argName: 'file', resolveValue: true },
	{ package: 'seqinr', name: 'read.fasta',      argIdx: 0, argName: 'file', resolveValue: true },
	/* shinyjs - loads an external JavaScript file */
	{ package: 'shinyjs', name: 'extendShinyjs', argIdx: 0, argName: 'script', resolveValue: true, ignoreIf: 'arg-missing' }
] as const;

export const ReadFunctions: FunctionInfo[] = [
	...ReadFunctionsWithMore,
	...functionInfosFromProps([SemanticCallTag.File, SemanticCallTag.Reads], [...ReadFunctionsWithMore, ...OtherPathFunctions])
];
