name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please make sure to include the way that you used flowR (e.g., the command you used).
      placeholder: Tell us what you see!
      value: "A bug happened when using the server!"
    validations:
      required: true
  - type: input
    id: r-version
    attributes:
      label: What version of R do you have installed?
      description: "You can use `R --version` to find out (with docker: `docker run --rm flowr --version`)."
      placeholder: ex. 4.2.3
    validations:
      required: false
  - type: input
    id: flowr-version
    attributes:
      label: What version of flowR did you use?
      description: "You can run flowr as `flowr --version` to find out (with docker: `docker run --rm flowr --version`)."
      options:
# START::Versions
        - v1.0.0
        - v1.1.0
        - v1.1.1
        - v1.1.2
        - v1.1.3
        - v1.1.4
        - v1.1.5
        - v1.1.6
        - v1.2.0
        - v1.2.1
        - v1.3.0
        - v1.3.1
        - v1.3.10
        - v1.3.11
        - v1.3.12
        - v1.3.13
        - v1.3.14
        - v1.3.2
        - v1.3.3
        - v1.3.4
        - v1.3.5
        - v1.3.6
        - v1.3.7
        - v1.3.8
        - v1.3.9
        - v1.4.0
        - v1.4.1
        - v1.4.2
        - v1.5.0
        - v1.5.1
        - v1.5.2
        - v2.0.0
        - v2.0.1
        - v2.0.10
        - v2.0.11
        - v2.0.12
        - v2.0.13
        - v2.0.14
        - v2.0.15
        - v2.0.16
        - v2.0.17
        - v2.0.18
        - v2.0.19
        - v2.0.2
        - v2.0.20
        - v2.0.21
        - v2.0.22
        - v2.0.23
        - v2.0.24
        - v2.0.25
        - v2.0.3
        - v2.0.4
        - v2.0.5
        - v2.0.6
        - v2.0.7
        - v2.0.8
        - v2.0.9
        - v2.1.0
        - v2.1.1
        - v2.1.10
        - v2.1.11
        - v2.1.12
        - v2.1.2
        - v2.1.3
        - v2.1.4
        - v2.1.5
        - v2.1.6
        - v2.1.7
        - v2.1.8
        - v2.1.9
        - v2.2.0
        - v2.2.1
        - v2.2.3
        - Unreleased/Dev 
# END::Versions
# START::DefaultVersion
      default: v2.2.3
# END::DefaultVersion
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Related input code
      description: If applicable, please copy and paste the input code here, best as a [MWE](https://stackoverflow.com/help/minimal-reproducible-example).
      render: R
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: checkboxes
    id: urgent
    attributes:
      label: Meta Information
      options:
        - label: The Issue is Urgent
          required: false
        - label: I Used the Dockerized Version of flowr
          required: false
