name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: input
    id: r-version
    attributes:
      label: What version of R do you have installed?
      description: "You can use `R --version` to find out (with docker: `docker run --rm flowr --version`)."
      placeholder: 4.4.2
    validations:
      required: false
  - type: dropdown
    id: flowr-version
    attributes:
      label: What version of flowR did you use?
      description: "You can run flowr as `flowr --version` to find out (with docker: `docker run --rm flowr --version`)."
      options:
# START::Versions
        - <Older> (please consider updating)
        - v2.2.13 (May 27, 2025)
        - v2.2.14 (May 31, 2025)
        - v2.2.15 (Jun 2, 2025)
        - v2.2.16 (Jul 12, 2025)
        - v2.3.0 (Jul 21, 2025)
        - v2.4.0 (Aug 6, 2025)
        - v2.4.1 (Aug 18, 2025)
        - v2.4.2 (Aug 19, 2025)
        - Unknown
        - Unreleased/Dev 
# END::Versions
# START::DefaultVersion
      default: 8
# END::DefaultVersion
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: checkboxes
    id: urgent
    attributes:
      label: Meta Information
      options:
        - label: The issue is urgent
          required: false
        - label: I used flowR as a docker image
          required: false
