name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: input
    id: r-version
    attributes:
      label: What version of R do you have installed?
      description: "You can use `R --version` to find out (with docker: `docker run --rm flowr --version`)."
      placeholder: 4.4.2
    validations:
      required: false
  - type: dropdown
    id: flowr-version
    attributes:
      label: What version of flowR did you use?
      description: "You can run flowr as `flowr --version` to find out (with docker: `docker run --rm flowr --version`)."
      options:
# START::Versions
        - v1.1.0 (Sep 15, 2023)
        - v1.1.1 (Sep 15, 2023)
        - v1.1.2 (Sep 15, 2023)
        - v1.1.3 (Sep 16, 2023)
        - v1.1.4 (Sep 24, 2023)
        - v1.1.5 (Sep 24, 2023)
        - v1.1.6 (Oct 10, 2023)
        - v1.2.0 (Oct 15, 2023)
        - v1.2.1 (Oct 18, 2023)
        - v1.3.0 (Oct 31, 2023)
        - v1.3.1 (Nov 2, 2023)
        - v1.3.2 (Nov 3, 2023)
        - v1.3.3 (Nov 10, 2023)
        - v1.3.4 (Nov 22, 2023)
        - v1.3.5 (Dec 8, 2023)
        - v1.3.6 (Dec 13, 2023)
        - v1.3.7 (Jan 4, 2024)
        - v1.3.8 (Jan 4, 2024)
        - v1.3.9 (Jan 4, 2024)
        - v1.3.10 (Jan 4, 2024)
        - v1.3.11 (Jan 4, 2024)
        - v1.3.12 (Jan 4, 2024)
        - v1.3.13 (Jan 13, 2024)
        - v1.3.14 (Jan 15, 2024)
        - v1.4.0 (Jan 31, 2024)
        - v1.4.1 (Jan 31, 2024)
        - v1.4.2 (Mar 17, 2024)
        - v1.5.0 (Mar 25, 2024)
        - v1.5.1 (Apr 4, 2024)
        - v1.5.2 (Apr 5, 2024)
        - v2.0.0 (May 11, 2024)
        - v2.0.1 (May 11, 2024)
        - v2.0.2 (May 28, 2024)
        - v2.0.3 (Jun 1, 2024)
        - v2.0.4 (Jun 2, 2024)
        - v2.0.5 (Jun 2, 2024)
        - v2.0.6 (Jun 3, 2024)
        - v2.0.7 (Jun 3, 2024)
        - v2.0.8 (Jun 4, 2024)
        - v2.0.9 (Jun 12, 2024)
        - v2.0.10 (Jun 25, 2024)
        - v2.0.11 (Jun 27, 2024)
        - v2.0.12 (Aug 14, 2024)
        - v2.0.13 (Aug 14, 2024)
        - v2.0.14 (Aug 14, 2024)
        - v2.0.15 (Aug 27, 2024)
        - v2.0.16 (Aug 28, 2024)
        - v2.0.17 (Aug 30, 2024)
        - v2.0.18 (Aug 31, 2024)
        - v2.0.19 (Sep 3, 2024)
        - v2.0.20 (Sep 9, 2024)
        - v2.0.21 (Sep 9, 2024)
        - v2.0.22 (Sep 12, 2024)
        - v2.0.23 (Sep 13, 2024)
        - v2.0.24 (Sep 13, 2024)
        - v2.0.25 (Sep 16, 2024)
        - v2.1.0 (Oct 4, 2024)
        - v2.1.1 (Oct 4, 2024)
        - v2.1.2 (Oct 12, 2024)
        - v2.1.3 (Oct 13, 2024)
        - v2.1.4 (Nov 3, 2024)
        - v2.1.5 (Nov 4, 2024)
        - v2.1.6 (Nov 14, 2024)
        - v2.1.7 (Nov 17, 2024)
        - v2.1.8 (Nov 28, 2024)
        - v2.1.9 (Dec 21, 2024)
        - v2.1.10 (Jan 5, 2025)
        - v2.1.11 (Jan 8, 2025)
        - v2.1.12 (Jan 10, 2025)
        - v2.2.0 (Jan 16, 2025)
        - v2.2.1 (Jan 16, 2025)
        - v2.2.3 (Feb 12, 2025)
        - Unknown
        - Unreleased/Dev 
# END::Versions
# START::DefaultVersion
      default: 71
# END::DefaultVersion
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Related input code
      description: If applicable, please copy and paste the input code here, best as a [MWE](https://stackoverflow.com/help/minimal-reproducible-example).
      render: R
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: checkboxes
    id: urgent
    attributes:
      label: Meta Information
      options:
        - label: The Issue is Urgent
          required: false
        - label: I Used the Dockerized Version of flowr
          required: false
