import { assert, describe, test } from 'vitest';
import { FlowrAnalyzerContext } from '../../../../src/project/context/flowr-analyzer-context';
import { arraysGroupBy } from '../../../../src/util/collections/arrays';
import { FlowrInlineTextFile } from '../../../../src/project/context/flowr-file';
import { FlowrConfig } from '../../../../src/config';
import {
	FlowrAnalyzerVirtualEnvFilePlugin
} from '../../../../src/project/plugins/file-plugins/flowr-analyzer-virtualenv-file-plugin';
import {
	FlowrAnalyzerPackageVersionsRenvPlugin,
	FlowrAnalyzerPackageVersionsRvPlugin
} from '../../../../src/project/plugins/package-version-plugins/flowr-analyzer-package-versions-lockfile-plugin';

/** an rv.lock as rv generates it, see https://a2-ai.github.io/rv-docs/ */
const rvLock = `# This file is automatically @generated by rv.
# It is not intended for manual editing.
version = 1
r_version = "4.5"

[[packages]]
name = "R6"
version = "2.6.1"
source = { repository = "https://packagemanager.posit.co/cran/2025-04-01" }
force_source = false
dependencies = []

[[packages]]
name = "MASS"
version = "7.3-65"
source = { builtin = true }
force_source = false
dependencies = []

[[packages]]
name = "ggplot2"
version = "3.5.1"
source = { repository = "https://packagemanager.posit.co/cran/2025-04-01" }
force_source = false
dependencies = [
    "cli",
    "glue",
]
`;

const renvLock = `{
  "R": { "Version": "4.4.1" },
  "Packages": {
    "R6": { "Package": "R6", "Version": "2.5.1" },
    "cli": { "Package": "cli", "Version": "3.6.4" }
  }
}`;

function ctxWith(name: string, content: string): FlowrAnalyzerContext {
	const ctx = new FlowrAnalyzerContext(
		FlowrConfig.default(),
		arraysGroupBy([
			new FlowrAnalyzerVirtualEnvFilePlugin(),
			new FlowrAnalyzerPackageVersionsRvPlugin(),
			new FlowrAnalyzerPackageVersionsRenvPlugin()
		], p => p.type)
	);
	ctx.addFile(new FlowrInlineTextFile(name, content));
	return ctx;
}

describe('Lockfile versions', () => {
	test('rv.lock pins every package, including builtin ones', () => {
		const ctx = ctxWith('rv.lock', rvLock);
		const got = ctx.deps.getDependencies().map(d => [d.name, d.versionConstraints[0]?.raw]);
		// `7.3-65` is an R version, where `-` separates a component just like `.` does
		assert.sameDeepMembers(got, [['R6', '2.6.1'], ['MASS', '7.3.65'], ['ggplot2', '3.5.1']]);
	});

	test('rv.lock contributes its r_version', () => {
		assert.strictEqual(ctxWith('rv.lock', rvLock).meta.getRVersion(), '4.5');
	});

	test('renv.lock pins every package', () => {
		const ctx = ctxWith('renv.lock', renvLock);
		const got = ctx.deps.getDependencies().map(d => [d.name, d.versionConstraints[0]?.raw]);
		assert.sameDeepMembers(got, [['R6', '2.5.1'], ['cli', '3.6.4']]);
	});

	test('a broken lockfile is skipped rather than throwing', () => {
		assert.deepStrictEqual(ctxWith('rv.lock', '[[packages]\nname = ').deps.getDependencies(), []);
		assert.deepStrictEqual(ctxWith('renv.lock', '{not json').deps.getDependencies(), []);
	});
});
