import { assert, describe, test } from 'vitest';
import { FlowrAnalyzerContext } from '../../../../src/project/context/flowr-analyzer-context';
import { arraysGroupBy } from '../../../../src/util/collections/arrays';
import { FlowrInlineTextFile } from '../../../../src/project/context/flowr-file';
import {
	FlowrAnalyzerNamespaceFilePlugin
} from '../../../../src/project/plugins/file-plugins/flowr-analyzer-namespace-file-plugin';
import {
	FlowrAnalyzerPackageVersionsNamespaceFilePlugin
} from '../../../../src/project/plugins/package-version-plugins/flowr-analyzer-package-versions-namespace-file-plugin';
import { defaultConfigOptions } from '../../../../src/config';


describe('NAMESPACE-file', function() {
	const ctx = new FlowrAnalyzerContext(
		defaultConfigOptions,
		arraysGroupBy([
			new FlowrAnalyzerNamespaceFilePlugin(),
			new FlowrAnalyzerPackageVersionsNamespaceFilePlugin()
		], p => p.type)
	);

	ctx.addFile(new FlowrInlineTextFile('NAMESPACE', `# Generated by roxygen2: do not edit by hand
S3method(fortify,data.frame)
S3method(fortify,lm)
S3method(fortify,default)
S3method(fortify,map)
S3method(scale_type,Date)
S3method(scale_type,POSIXt)
S3method(scale_type,character)
S3method(scale_type,numeric)
S3method(scale_type,factor)
S3method(scale_type,default)
S3method(ggplot,default)
S3method(print,ggproto)
S3method(print,rel)
export(ggplot)
export(aes)
export(geom_point)
export(geom_line)
export(theme_bw)
export(coord_cartesian)
export(ggsave)
export(fortify)
export(scale_type)
import(grid)
import(rlang)
importFrom(scales,alpha)
importFrom(stats,setNames)`));

	ctx.addFile(new FlowrInlineTextFile('test.R', 'x <- 1'));
	ctx.addRequests([{ request: 'file', content: 'test.R' }]);
	ctx.resolvePreAnalysis();

	describe.sequential('Basic exports', function() {
		test('Functions are exported', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'ggplot'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'aes'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'geom_point'));
		});

		test('Correct total number of exports', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.strictEqual(deps.namespaceInfo?.exportedSymbols.length, 9);
		});

		test('All export names present', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('ggplot'));
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('coord_cartesian'));
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('ggsave'));
		});
	});

	describe.sequential('S3 methods - fortify', function() {
		test('All fortify methods registered in namespaceInfo', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);

			const fortifyMethods = deps.namespaceInfo?.exportS3Generics.get('fortify');
			assert.isDefined(fortifyMethods);
			assert.strictEqual(fortifyMethods.length, 4);
			assert.isTrue(fortifyMethods?.includes('data.frame'));
			assert.isTrue(fortifyMethods?.includes('lm'));
		});

		test('Specific fortify classes accessible', () => {
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'data.frame'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'lm'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'default'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'map'));

			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.isTrue(deps.namespaceInfo?.exportS3Generics.get('fortify')?.length === 4);
		});
	});

	describe.sequential('Mixed exports and S3', function() {
		test('ggplot has export and S3 method', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);

			// Export
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('ggplot'));

			// S3 method
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'ggplot', 'default'));
			assert.isTrue(deps.namespaceInfo?.exportS3Generics.has('ggplot'));
		});

		test('Total S3 generics count', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.strictEqual(deps.namespaceInfo?.exportS3Generics.size, 4);
		});
	});
});