import { assert, describe, test } from 'vitest';
import { FlowrAnalyzerContext } from '../../../../src/project/context/flowr-analyzer-context';
import { arraysGroupBy } from '../../../../src/util/collections/arrays';
import { FlowrInlineTextFile } from '../../../../src/project/context/flowr-file';
import {
	FlowrAnalyzerNamespaceFilesPlugin
} from '../../../../src/project/plugins/file-plugins/flowr-analyzer-namespace-files-plugin';
import {
	FlowrAnalyzerPackageVersionsNamespaceFilePlugin
} from '../../../../src/project/plugins/package-version-plugins/flowr-analyzer-package-versions-namespace-file-plugin';
import { FlowrNamespaceFile, isExportedInInfo } from '../../../../src/project/plugins/file-plugins/files/flowr-namespace-file';
import { FlowrConfig } from '../../../../src/config';


describe('NAMESPACE-file', function() {
	const ctx = new FlowrAnalyzerContext(
		FlowrConfig.default(),
		arraysGroupBy([
			new FlowrAnalyzerNamespaceFilesPlugin(),
			new FlowrAnalyzerPackageVersionsNamespaceFilePlugin()
		], p => p.type)
	);

	ctx.addFile(new FlowrInlineTextFile('NAMESPACE', `# Generated by roxygen2: do not edit by hand
S3method(fortify,data.frame)
S3method(fortify,lm)
S3method(fortify,default)
S3method(fortify,map)
S3method(scale_type,Date)
S3method(scale_type,POSIXt)
S3method(scale_type,character)
S3method(scale_type,numeric)
S3method(scale_type,factor)
S3method(scale_type,default)
S3method(ggplot,default)
S3method(print,ggproto)
S3method(print,rel)
export("+")
export(ggplot)
export(aes)
export(geom_point)
export(geom_line)
export(theme_bw)
export(coord_cartesian)
export(ggsave)
export(fortify)
export(scale_type)
exportPattern("^[^\\.]\\.*$")
import(grid)
import(rlang)
importFrom(scales,alpha)
importFrom(stats,setNames)
importClassesFrom(Matrix,dgCMatrix)
importMethodsFrom(BiocGenerics,combine)`));

	ctx.addFile(new FlowrInlineTextFile('test.R', 'x <- 1'));
	ctx.addRequests([{ request: 'file', content: 'test.R' }]);

	describe('Basic exports', function() {
		test('Functions are exported', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'ggplot'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'aes'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'geom_point'));
		});

		test('Correct total number of exports', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.strictEqual(deps.namespaceInfo?.exportedSymbols.length, 10);
		});

		test('All export names present', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('+'));
			assert.isFalse(deps.namespaceInfo?.exportedSymbols.includes('"+"'));
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('ggplot'));
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('coord_cartesian'));
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('ggsave'));
		});

		test('Export pattern registered', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.strictEqual(deps.namespaceInfo?.exportedPatterns?.length, 1);
			assert.strictEqual(deps.namespaceInfo?.exportedPatterns?.[0], '^[^\\.]\\.*$');
		});

		test('isExported', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps?.namespaceInfo);
			assert.isFalse(isExportedInInfo('ggplot2', deps?.namespaceInfo));
			assert.isTrue(isExportedInInfo('ggplot', deps?.namespaceInfo));
		});
	});

	describe('S3 methods - fortify', function() {
		test('All fortify methods registered in namespaceInfo', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);

			const fortifyMethods = deps.namespaceInfo?.exportS3Generics.get('fortify');
			assert.isDefined(fortifyMethods);
			assert.strictEqual(fortifyMethods.length, 4);
			assert.isTrue(fortifyMethods?.includes('data.frame'));
			assert.isTrue(fortifyMethods?.includes('lm'));
		});

		test('Specific fortify classes accessible', () => {
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'data.frame'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'lm'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'default'));
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'fortify', 'map'));

			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.isTrue(deps.namespaceInfo?.exportS3Generics.get('fortify')?.length === 4);
		});
	});

	describe('Correct Imports', function() {
		test('Imports are registered correctly', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);

			assert.isTrue(deps.namespaceInfo?.importedPackages?.has('grid'));
			assert.isTrue(deps.namespaceInfo?.importedPackages?.has('rlang'));
			assert.isTrue(deps.namespaceInfo?.importedPackages?.has('scales'));
			assert.isTrue(deps.namespaceInfo?.importedPackages?.has('stats'));

			assert.strictEqual(deps.namespaceInfo?.importedPackages?.get('grid'), 'all');
			assert.strictEqual(deps.namespaceInfo?.importedPackages?.get('rlang'), 'all');
			assert.deepEqual(deps.namespaceInfo?.importedPackages?.get('scales'), ['alpha']);
			assert.deepEqual(deps.namespaceInfo?.importedPackages?.get('stats'), ['setNames']);
		});

		test('importClassesFrom / importMethodsFrom register their source package (S4)', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.deepEqual(deps.namespaceInfo?.importedPackages?.get('Matrix'), ['dgCMatrix']);
			assert.deepEqual(deps.namespaceInfo?.importedPackages?.get('BiocGenerics'), ['combine']);
		});
	});

	describe('Simple parser (no analyzer context): multi-symbol directives', function() {
		/** parse a NAMESPACE string with the regex-based fallback (`parseNamespaceSimple`, used when no ctx is present) */
		const simple = (content: string) => new FlowrNamespaceFile(new FlowrInlineTextFile('NAMESPACE', content)).content();

		test('export(a, b) exports both symbols, not the literal "a, b"', () => {
			const info = simple('export(alpha, beta, gamma)').current;
			assert.deepEqual(info.exportedSymbols, ['alpha', 'beta', 'gamma']);
			assert.isFalse(info.exportedSymbols.includes('alpha, beta, gamma'));
		});

		test('exportMethods / exportClasses split their arguments too', () => {
			const info = simple('exportMethods(show, summary)\nexportClasses("A", "B")').current;
			assert.includeMembers(info.exportedFunctions, ['show', 'summary', 'A', 'B']);
			assert.strictEqual(info.exportedFunctions.length, 4);
		});

		test('single-symbol and quoted exports still parse (no regression)', () => {
			const info = simple('export("+")\nexport(ggplot)').current;
			assert.includeMembers(info.exportedSymbols, ['+', 'ggplot']);
			assert.isFalse(info.exportedSymbols.includes('"+"'));
		});

		test('importClassesFrom / importMethodsFrom record the source package like importFrom', () => {
			const info = simple('importClassesFrom(Matrix, dgCMatrix, dgeMatrix)\nimportMethodsFrom(BiocGenerics, combine)').current;
			assert.deepEqual(info.importedPackages.get('Matrix'), ['dgCMatrix', 'dgeMatrix']);
			assert.deepEqual(info.importedPackages.get('BiocGenerics'), ['combine']);
		});
	});

	describe('Mixed exports and S3', function() {
		test('ggplot has export and S3 method', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);

			// Export
			assert.isTrue(deps.namespaceInfo?.exportedSymbols.includes('ggplot'));

			// S3 method
			assert.isDefined(ctx.deps.functionsContext.getFunctionInfo('current', 'ggplot', 'default'));
			assert.isTrue(deps.namespaceInfo?.exportS3Generics.has('ggplot'));
		});

		test('Total S3 generics count', () => {
			const deps = ctx.deps.getDependency('current');
			assert.isDefined(deps);
			assert.strictEqual(deps.namespaceInfo?.exportS3Generics.size, 4);
		});
	});
});