FROM mcr.microsoft.com/devcontainers/typescript-node

# Install dependencies
RUN apt update && \
    apt upgrade -y && \
    apt install -y git openssh-client ssh vim r-base r-base-dev r-cran-xmlparsedata
