import { afterEach, describe, expect, test } from 'vitest';
import { label } from '../../../_helper/label';
import { downloadFullSigDb, sha256File, SigDbDownloadError, syncedSigDbDir, sigDbNeedsSync, type SigDbRemote } from '../../../../../src/project/sigdb/sigdb-download';
import crypto from 'crypto';
import http from 'http';
import type { AddressInfo } from 'net';
import { sigDbBundleDirs } from '../../../../../src/project/sigdb/manifest';
import { writeRemotePointer } from '../../../../../scripts/sigdb-remote';
import fs from 'fs';
import os from 'os';
import path from 'path';

/**
 * Covers the local (no-network) half of the auto-sync mechanism: the committed link file is generated by
 * `writeRemotePointer`, and the runtime decides whether a re-sync is due purely from that pointer plus the
 * hash-keyed cache ({@link sigDbNeedsSync}/{@link syncedSigDbDir}). The download itself runs against a local mirror.
 */
describe('SigDb auto-sync (pointer)', { concurrent: false }, () => {
	const cleanups: (() => void)[] = [];
	afterEach(() => {
		while(cleanups.length) {
			cleanups.pop()?.();
		}
	});

	test(label('writeRemotePointer records every `.br` shard (base floor + CRAN sets), skipping non-shard files', [], ['other']), async() => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'flowr-remote-'));
		cleanups.push(() => fs.rmSync(dir, { recursive: true, force: true }));
		// two `.br` shards (base floor + a CRAN shard, both downloadable) and a non-shard file (ignored)
		fs.writeFileSync(path.join(dir, 'current.current-top.sigs.ndjson.br'), 'HOTSHARD');
		fs.writeFileSync(path.join(dir, 'base.dict.sigs.ndjson.br'), 'FLOOR');
		fs.writeFileSync(path.join(dir, 'current.manifest.json'), '{}');

		const res = await writeRemotePointer({ bundleDir: dir, tag: 'sigdb-v9.9.9', repo: 'acme/flowr', skipVerification: true });
		expect(res.downloadable).toEqual(['base.dict.sigs.ndjson.br', 'current.current-top.sigs.ndjson.br']);

		const written = JSON.parse(fs.readFileSync(path.join(dir, 'sigdb.remote.json'), 'utf8')) as SigDbRemote;
		expect(written.tag).toBe('sigdb-v9.9.9');
		expect(written.repo).toBe('acme/flowr');
		// nothing is committed anymore: the base floor is listed for download alongside the CRAN shards
		expect(Object.keys(written.shards).sort()).toEqual(['base.dict.sigs.ndjson.br', 'current.current-top.sigs.ndjson.br']);
		const shard = written.shards['base.dict.sigs.ndjson.br'];
		expect(shard.sha256).toBe(sha256File(path.join(dir, 'base.dict.sigs.ndjson.br')));
		expect(shard.bytes).toBe('FLOOR'.length);
	});

	test(label('sigDbNeedsSync is true and syncedSigDbDir points into an empty cache', [], ['other']), () => {
		// the committed pointer names real shards; an empty cache has none of them -> a sync is due
		const cache = fs.mkdtempSync(path.join(os.tmpdir(), 'flowr-cache-'));
		const prev = process.env.FLOWR_SIGDB_CACHE;
		process.env.FLOWR_SIGDB_CACHE = cache;
		cleanups.push(() => {
			if(prev === undefined) {
				delete process.env.FLOWR_SIGDB_CACHE;
			} else {
				process.env.FLOWR_SIGDB_CACHE = prev;
			}
			fs.rmSync(cache, { recursive: true, force: true });
		});

		const dir = syncedSigDbDir();
		// only meaningful when this checkout ships a committed link file
		if(dir === undefined) {
			expect(sigDbNeedsSync()).toBe(false);
			return;
		}
		expect(dir.startsWith(cache)).toBe(true);
		expect(sigDbNeedsSync()).toBe(true);
	});

	function restoreEnv(key: 'FLOWR_SIGDB_CACHE' | 'FLOWR_SIGDB_REMOTE' | 'FLOWR_SIGDB_MIRROR', value: string | undefined): void {
		if(value !== undefined) {
			process.env[key] = value;
		} else if(key === 'FLOWR_SIGDB_CACHE') {
			delete process.env.FLOWR_SIGDB_CACHE;
		} else if(key === 'FLOWR_SIGDB_REMOTE') {
			delete process.env.FLOWR_SIGDB_REMOTE;
		} else {
			delete process.env.FLOWR_SIGDB_MIRROR;
		}
	}

	/** a cache dir and a link file naming the given shards (the contents are what the release serves) */
	function setupRemote(shards: Record<string, string>): { dir: string } {
		const root = fs.mkdtempSync(path.join(os.tmpdir(), 'flowr-sync-'));
		const remote: SigDbRemote = {
			tag:    'sigdb-test',
			repo:   'acme/flowr',
			shards: Object.fromEntries(Object.entries(shards).map(([name, content]) => [name, {
				sha256: crypto.createHash('sha256').update(content).digest('hex'),
				bytes:  Buffer.byteLength(content)
			}]))
		};
		const pointer = path.join(root, 'sigdb.remote.json');
		fs.writeFileSync(pointer, JSON.stringify(remote));
		const prev = { cache: process.env.FLOWR_SIGDB_CACHE, remote: process.env.FLOWR_SIGDB_REMOTE };
		process.env.FLOWR_SIGDB_CACHE = path.join(root, 'cache');
		process.env.FLOWR_SIGDB_REMOTE = pointer;
		cleanups.push(() => {
			restoreEnv('FLOWR_SIGDB_CACHE', prev.cache);
			restoreEnv('FLOWR_SIGDB_REMOTE', prev.remote);
			fs.rmSync(root, { recursive: true, force: true });
		});
		return { dir: path.join(root, 'cache', 'sigdb', 'bundles', 'sigdb-test') };
	}

	/** serve the assets from a local mirror; `respond` gives the status and body per asset name */
	async function serve(respond: (name: string) => { status: number, body?: string }): Promise<string[]> {
		const requested: string[] = [];
		const server = http.createServer((req, res) => {
			const name = decodeURIComponent((req.url ?? '').slice((req.url ?? '').lastIndexOf('/') + 1));
			requested.push(name);
			const { status, body } = respond(name);
			res.writeHead(status);
			res.end(body);
		});
		await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
		const prev = process.env.FLOWR_SIGDB_MIRROR;
		process.env.FLOWR_SIGDB_MIRROR = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
		cleanups.push(() => {
			restoreEnv('FLOWR_SIGDB_MIRROR', prev);
			server.close();
		});
		return requested;
	}

	test(label('a sync fetches one codec per shard, verifies it, and is complete afterwards', [], ['other']), async() => {
		const { dir } = setupRemote({
			'base.dict.sigs.ndjson.br':  'DICT-BR',
			'base.dict.sigs.ndjson.zst': 'DICT-ZST',
			'base.manifest.json.br':     'MANIFEST-BR',
			'base.manifest.json.zst':    'MANIFEST-ZST'
		});
		const served: Record<string, string> = { 'base.dict.sigs.ndjson.br': 'DICT-BR', 'base.dict.sigs.ndjson.zst': 'DICT-ZST', 'base.manifest.json.br': 'MANIFEST-BR', 'base.manifest.json.zst': 'MANIFEST-ZST' };
		const requested = await serve(name => ({ status: 200, body: served[name] }));
		expect(sigDbNeedsSync()).toBe(true);
		const messages: string[] = [];
		const res = await downloadFullSigDb({ onProgress: m => messages.push(m) });
		expect(requested).toHaveLength(2);
		// the manifest comes last, so it never references shards that are not there yet
		expect(requested[1]).toMatch(/manifest/);
		expect(res.downloaded).toHaveLength(2);
		expect(res.manifest?.startsWith(dir)).toBe(true);
		expect(messages.some(m => m.includes('checksum verified'))).toBe(true);
		// the variants we did not pick must not keep the sync pending forever
		expect(sigDbNeedsSync()).toBe(false);

		const again = await downloadFullSigDb({ onProgress: m => messages.push(m) });
		expect(again.downloaded).toHaveLength(0);
		expect(requested).toHaveLength(2);
		expect(messages.at(-1)).toMatch(/up to date/);
	});

	test(label('a corrupt or failing download leaves no file behind and does not stop the others', [], ['other']), async() => {
		const { dir } = setupRemote({
			'base.dict.sigs.ndjson.br':            'GOOD',
			'current.current-top.sigs.ndjson.br':  'EXPECTED',
			'current.current-rest.sigs.ndjson.br': 'GONE',
			'base.manifest.json.br':               'MANIFEST'
		});
		await serve(name => name.includes('top') ? { status: 200, body: 'TAMPERED' } : name.includes('rest') ? { status: 404 } : { status: 200, body: name.includes('dict') ? 'GOOD' : 'MANIFEST' });
		const err = await downloadFullSigDb().catch((e: unknown) => e);
		expect(err).toBeInstanceOf(SigDbDownloadError);
		const failed = (err as SigDbDownloadError).failed.map(f => f.name).sort();
		// the manifest is held back as it references the missing shards
		expect(failed).toEqual(['base.manifest.json.br', 'current.current-rest.sigs.ndjson.br', 'current.current-top.sigs.ndjson.br']);
		expect((err as SigDbDownloadError).failed.find(f => f.name.includes('top'))?.reason).toMatch(/sha256 mismatch/);
		expect(fs.readdirSync(dir)).toEqual(['base.dict.sigs.ndjson.br']);
	});

	test(label('a transient server error is retried', [], ['other']), async() => {
		setupRemote({ 'base.dict.sigs.ndjson.br': 'DICT' });
		let attempts = 0;
		await serve(() => ++attempts === 1 ? { status: 503 } : { status: 200, body: 'DICT' });
		const res = await downloadFullSigDb();
		expect(attempts).toBe(2);
		expect(res.downloaded).toHaveLength(1);
	});

	test(label('the most recently synced bundle takes precedence over older releases in the cache', [], ['other']), async() => {
		const { dir } = setupRemote({ 'base.dict.sigs.ndjson.br': 'DICT' });
		await serve(() => ({ status: 200, body: 'DICT' }));
		/* an older release whose tag sorts after the new one */
		const older = path.join(path.dirname(dir), 'zz-older');
		fs.mkdirSync(older, { recursive: true });
		const past = new Date(Date.now() - 60_000);
		fs.utimesSync(older, past, past);
		const messages: string[] = [];
		await downloadFullSigDb({ onProgress: m => messages.push(m) });
		expect(sigDbBundleDirs()).toEqual([dir, older]);
		expect(messages.at(-1)).toMatch(/zz-older/);
		/* syncing again with nothing to fetch still makes it the most recent one */
		fs.utimesSync(older, new Date(), new Date());
		await downloadFullSigDb();
		expect(sigDbBundleDirs()[0]).toBe(dir);
	});
});
