import { afterEach, describe, expect, test } from 'vitest';
import { label } from '../../../_helper/label';
import { sha256File, syncedSigDbDir, sigDbNeedsSync, type SigDbRemote } from '../../../../../src/project/plugins/package-version-plugins/sigdb-download';
import { writeRemotePointer } from '../../../../../scripts/sigdb-remote';
import fs from 'fs';
import os from 'os';
import path from 'path';

/**
 * Covers the local (no-network) half of the auto-sync mechanism: the committed link file is generated by
 * `writeRemotePointer`, and the runtime decides whether a re-sync is due purely from that pointer plus the
 * hash-keyed cache ({@link sigDbNeedsSync}/{@link syncedSigDbDir}). The actual HTTP download is not unit-tested.
 */
describe('SigDb auto-sync (pointer)', () => {
	const cleanups: (() => void)[] = [];
	afterEach(() => {
		while(cleanups.length) {
			cleanups.pop()?.();
		}
	});

	test(label('writeRemotePointer records the downloadable shards (sha256 + size) and excludes the base floor', [], ['other']), () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'flowr-remote-'));
		cleanups.push(() => fs.rmSync(dir, { recursive: true, force: true }));
		// a downloadable shard, a base-floor shard (excluded), and a non-shard file (ignored)
		fs.writeFileSync(path.join(dir, 'current.current-top.sigs.ndjson.br'), 'HOTSHARD');
		fs.writeFileSync(path.join(dir, 'base.dict.sigs.ndjson.br'), 'FLOOR');
		fs.writeFileSync(path.join(dir, 'current.manifest.json'), '{}');

		const res = writeRemotePointer({ bundleDir: dir, tag: 'sigdb-v9.9.9', repo: 'acme/flowr' });
		expect(res.downloadable).toEqual(['current.current-top.sigs.ndjson.br']);

		const written = JSON.parse(fs.readFileSync(path.join(dir, 'sigdb.remote.json'), 'utf8')) as SigDbRemote;
		expect(written.tag).toBe('sigdb-v9.9.9');
		expect(written.repo).toBe('acme/flowr');
		// the base floor is never listed (it ships in git)
		expect(Object.keys(written.shards)).toEqual(['current.current-top.sigs.ndjson.br']);
		const shard = written.shards['current.current-top.sigs.ndjson.br'];
		expect(shard.sha256).toBe(sha256File(path.join(dir, 'current.current-top.sigs.ndjson.br')));
		expect(shard.bytes).toBe('HOTSHARD'.length);
	});

	test(label('sigDbNeedsSync is true and syncedSigDbDir points into an empty cache', [], ['other']), () => {
		// the committed pointer names real shards; an empty cache has none of them -> a sync is due
		const cache = fs.mkdtempSync(path.join(os.tmpdir(), 'flowr-cache-'));
		const prev = process.env.FLOWR_SIGDB_CACHE;
		process.env.FLOWR_SIGDB_CACHE = cache;
		cleanups.push(() => {
			if(prev === undefined) {
				delete process.env.FLOWR_SIGDB_CACHE;
			} else {
				process.env.FLOWR_SIGDB_CACHE = prev;
			}
			fs.rmSync(cache, { recursive: true, force: true });
		});

		const dir = syncedSigDbDir();
		// only meaningful when this checkout ships a committed link file
		if(dir === undefined) {
			expect(sigDbNeedsSync()).toBe(false);
			return;
		}
		expect(dir.startsWith(cache)).toBe(true);
		expect(sigDbNeedsSync()).toBe(true);
	});
});
