/**
 * Generated from R source names.c
 * @see {@link https://github.com/wch/r-source/blob/2196e6982a8f49082ee5c3d3521f6dd6596ea72c/src/main/names.c#L83-L1017}
 * Do not edit manually.
 */

export enum PPKind {
	Invalid       = 'PP_INVALID',
	Assign        = 'PP_ASSIGN',
	Assign2       = 'PP_ASSIGN2',
	Binary        = 'PP_BINARY',
	Binary2       = 'PP_BINARY2',
	Break         = 'PP_BREAK',
	Curly         = 'PP_CURLY',
	For           = 'PP_FOR',
	FunCall       = 'PP_FUNCALL',
	Function      = 'PP_FUNCTION',
	If            = 'PP_IF',
	Next          = 'PP_NEXT',
	Paren         = 'PP_PAREN',
	Repeat        = 'PP_REPEAT',
	Return        = 'PP_RETURN',
	SubAss        = 'PP_SUBASS',
	Subset        = 'PP_SUBSET',
	Unary         = 'PP_UNARY',
	While         = 'PP_WHILE',
	Dollar        = 'PP_DOLLAR',
	Foreign       = 'PP_FOREIGN',
	Tilde         = 'PP_TILDE',
}

export enum Precedence {
	Fn      = 'PREC_FN',
	Left    = 'PREC_LEFT',
	Eq      = 'PREC_EQ',
	Right   = 'PREC_RIGHT',
	Tilde   = 'PREC_TILDE',
	Or      = 'PREC_OR',
	And     = 'PREC_AND',
	Not     = 'PREC_NOT',
	Compare = 'PREC_COMPARE',
	Sum     = 'PREC_SUM',
	Prod    = 'PREC_PROD',
	Percent = 'PREC_PERCENT',
	Colon   = 'PREC_COLON',
	Sign    = 'PREC_SIGN',
	Power   = 'PREC_POWER',
	Subset  = 'PREC_SUBSET',
	Dollar  = 'PREC_DOLLAR',
	Ns      = 'PREC_NS',
}

export interface FunTabEntry {
	/** R function name (printname) */
	name:       string;
	/** C entry point name */
	cEntry:     string;
	/** Offset passed to the C function */
	offset:     number | string;
	/** Eval flags */
	eval:       number;
	/** Arity (-1 = variadic) */
	arity:      number;
	/** Pretty-print kind */
	ppKind:     PPKind;
	/** Operator precedence */
	precedence: Precedence;
	/** Right-associative flag */
	rightAssoc: 0 | 1;
}

const e = (
	name: string,
	cEntry: string,
	offset: number | string,
	evalFlag: number,
	arity: number,
	ppKind: PPKind,
	precedence: Precedence,
	rightAssoc: 0 | 1
): FunTabEntry => ({ name, cEntry, offset, eval: evalFlag, arity, ppKind, precedence, rightAssoc });

const FN = PPKind.FunCall;
const PREC = Precedence.Fn;

/**
 * R primitive function table.
 * @see {@link https://github.com/wch/r-source/blob/2196e6982a8f49082ee5c3d3521f6dd6596ea72c/src/main/names.c#L83-L1017 | R source: names.c}
 */
export const RFunTab: FunTabEntry[] = [
	/* -- Language Related Constructs -- */
	e('if',           'do_if',           0,           200,  -1, PPKind.If,       PREC,               1),
	e('while',        'do_while',        0,           100,   2, PPKind.While,    PREC,               0),
	e('for',          'do_for',          0,           100,   3, PPKind.For,      PREC,               0),
	e('repeat',       'do_repeat',       0,           100,   1, PPKind.Repeat,   PREC,               0),
	e('break',        'do_break',        'CTXT_BREAK',  0,   0, PPKind.Break,    PREC,               0),
	e('next',         'do_break',        'CTXT_NEXT',   0,   0, PPKind.Next,     PREC,               0),
	e('return',       'do_return',       0,             0,  -1, PPKind.Return,   PREC,               0),
	e('function',     'do_function',     0,             0,  -1, PPKind.Function, PREC,               0),
	e('<-',           'do_set',          1,           100,  -1, PPKind.Assign,   Precedence.Left,    1),
	e('=',            'do_set',          3,           100,  -1, PPKind.Assign,   Precedence.Eq,      1),
	e('<<-',          'do_set',          2,           100,  -1, PPKind.Assign2,  Precedence.Left,    1),
	e('{',            'do_begin',        0,           200,  -1, PPKind.Curly,    PREC,               0),
	e('(',            'do_paren',        0,             1,   1, PPKind.Paren,    PREC,               0),
	e('.subset',      'do_subset_dflt',  1,             1,  -1, FN,              PREC,               0),
	e('.subset2',     'do_subset2_dflt', 2,             1,  -1, FN,              PREC,               0),
	e('[',            'do_subset',       1,             0,  -1, PPKind.Subset,   Precedence.Subset,  0),
	e('[[',           'do_subset2',      2,             0,  -1, PPKind.Subset,   Precedence.Subset,  0),
	e('$',            'do_subset3',      3,             0,   2, PPKind.Dollar,   Precedence.Dollar,  0),
	e('@',            'do_AT',           0,             0,   2, PPKind.Dollar,   Precedence.Dollar,  0),
	e('[<-',          'do_subassign',    0,             0,   3, PPKind.SubAss,   Precedence.Left,    1),
	e('[[<-',         'do_subassign2',   1,             0,   3, PPKind.SubAss,   Precedence.Left,    1),
	e('$<-',          'do_subassign3',   1,             0,   3, PPKind.SubAss,   Precedence.Left,    1),
	e('switch',       'do_switch',       0,           200,  -1, FN,              PREC,               0),
	e('browser',      'do_browser',      0,           101,  -1, FN,              PREC,               0),
	e('.primTrace',   'do_trace',        0,           101,   1, FN,              PREC,               0),
	e('.primUntrace', 'do_trace',        1,           101,   1, FN,              PREC,               0),
	e('.Internal',    'do_internal',     0,           200,   1, FN,              PREC,               0),
	e('.Primitive',   'do_primitive',    0,             1,   1, FN,              PREC,               0),
	e('call',         'do_call',         0,             0,  -1, FN,              PREC,               0),
	e('quote',        'do_quote',        0,             0,   1, FN,              PREC,               0),
	e('substitute',   'do_substitute',   0,             0,  -1, FN,              PREC,               0),
	e('missing',      'do_missing',      1,             0,   1, FN,              PREC,               0),
	e('nargs',        'do_nargs',        1,             1,   0, FN,              PREC,               0),
	e('on.exit',      'do_onexit',       0,           100,  -1, FN,              PREC,               0),
	e('forceAndCall', 'do_forceAndCall', 0,             0,  -1, FN,              PREC,               0),
	e('declare',      'do_declare',      0,           100,  -1, FN,              PREC,               0),

	/* -- .Internals -- */
	e('stop',                   'do_stop',                  0,    11,  2, FN, PREC, 0),
	e('warning',                'do_warning',               0,   111,  4, FN, PREC, 0),
	e('gettext',                'do_gettext',               0,    11,  3, FN, PREC, 0),
	e('ngettext',               'do_ngettext',              0,    11,  4, FN, PREC, 0),
	e('bindtextdomain',         'do_bindtextdomain',        0,    11,  2, FN, PREC, 0),
	e('.addCondHands',          'do_addCondHands',          0,   111,  5, FN, PREC, 0),
	e('.addGlobHands',          'do_addGlobHands',          0,   111,  5, FN, PREC, 0),
	e('.resetCondHands',        'do_resetCondHands',        0,   111,  1, FN, PREC, 0),
	e('.signalCondition',       'do_signalCondition',       0,    11,  3, FN, PREC, 0),
	e('.dfltStop',              'do_dfltStop',              0,    11,  2, FN, PREC, 0),
	e('.dfltWarn',              'do_dfltWarn',              0,    11,  2, FN, PREC, 0),
	e('.addRestart',            'do_addRestart',            0,    11,  1, FN, PREC, 0),
	e('.getRestart',            'do_getRestart',            0,    11,  1, FN, PREC, 0),
	e('.invokeRestart',         'do_invokeRestart',         0,    11,  2, FN, PREC, 0),
	e('.addTryHandlers',        'do_addTryHandlers',        0,   111,  0, FN, PREC, 0),
	e('geterrmessage',          'do_geterrmessage',         0,    11,  0, FN, PREC, 0),
	e('seterrmessage',          'do_seterrmessage',         0,   111,  1, FN, PREC, 0),
	e('printDeferredWarnings',  'do_printDeferredWarnings', 0,   111,  0, FN, PREC, 0),
	e('interruptsSuspended',    'do_interruptsSuspended',   0,    11, -1, FN, PREC, 0),
	e('as.function.default',    'do_asfunction',            0,    11,  2, PPKind.Function, PREC, 0),
	e('debug',                  'do_debug',                 0,   111,  3, FN, PREC, 0),
	e('undebug',                'do_debug',                 1,   111,  1, FN, PREC, 0),
	e('isdebugged',             'do_debug',                 2,    11,  1, FN, PREC, 0),
	e('debugonce',              'do_debug',                 3,   111,  3, FN, PREC, 0),
	e('Recall',                 'do_recall',                0,   210, -1, FN, PREC, 0),
	e('delayedAssign',          'do_delayed',               0,   111,  4, FN, PREC, 0),
	e('makeLazy',               'do_makelazy',              0,   111,  5, FN, PREC, 0),
	e('identical',              'do_identical',             0,    11,  8, FN, PREC, 0),
	e('C_tryCatchHelper',       'do_tryCatchHelper',        0,    11, -1, FN, PREC, 0),
	e('getNamespaceValue',      'do_getNSValue',            0,   211,  3, FN, PREC, 0),

	/* -- Binary Operators -- */
	e('+',   'do_arith',   'PLUSOP',  1, -1, PPKind.Binary,  Precedence.Sum,     0),
	e('-',   'do_arith',   'MINUSOP', 1, -1, PPKind.Binary,  Precedence.Sum,     0),
	e('*',   'do_arith',   'TIMESOP', 1,  2, PPKind.Binary,  Precedence.Prod,    0),
	e('/',   'do_arith',   'DIVOP',   1,  2, PPKind.Binary2, Precedence.Prod,    0),
	e('^',   'do_arith',   'POWOP',   1,  2, PPKind.Binary2, Precedence.Power,   1),
	e('%%',  'do_arith',   'MODOP',   1,  2, PPKind.Binary2, Precedence.Percent, 0),
	e('%/%', 'do_arith',   'IDIVOP',  1,  2, PPKind.Binary2, Precedence.Percent, 0),
	e('%*%', 'do_matprod', 0,         1,  2, PPKind.Binary,  Precedence.Percent, 0),

	e('==', 'do_relop', 'EQOP', 1, 2, PPKind.Binary, Precedence.Compare, 0),
	e('!=', 'do_relop', 'NEOP', 1, 2, PPKind.Binary, Precedence.Compare, 0),
	e('<',  'do_relop', 'LTOP', 1, 2, PPKind.Binary, Precedence.Compare, 0),
	e('<=', 'do_relop', 'LEOP', 1, 2, PPKind.Binary, Precedence.Compare, 0),
	e('>=', 'do_relop', 'GEOP', 1, 2, PPKind.Binary, Precedence.Compare, 0),
	e('>',  'do_relop', 'GTOP', 1, 2, PPKind.Binary, Precedence.Compare, 0),

	e('&',  'do_logic',  1, 1, 2, PPKind.Binary, Precedence.And, 0),
	e('|',  'do_logic',  2, 1, 2, PPKind.Binary, Precedence.Or,  0),
	e('!',  'do_logic',  3, 1, 1, PPKind.Unary,  Precedence.Not, 0),
	e('&&', 'do_logic2', 1, 0, 2, PPKind.Binary, Precedence.And, 0),
	e('||', 'do_logic2', 2, 0, 2, PPKind.Binary, Precedence.Or,  0),
	e(':',  'do_colon',  0, 1, 2, PPKind.Binary2, Precedence.Colon, 0),
	e('~',  'do_tilde',  0, 0, -1, PPKind.Binary, Precedence.Tilde, 0),
	e('::',  'do_colon2', 0, 200, 2, PPKind.Binary2, Precedence.Ns, 0),
	e(':::', 'do_colon3', 0, 200, 2, PPKind.Binary2, Precedence.Ns, 0),

	/* -- Logic -- */
	e('all', 'do_logic3', 1, 1, -1, FN, PREC, 0),
	e('any', 'do_logic3', 2, 1, -1, FN, PREC, 0),

	/* -- Vectors / Matrices / Arrays -- */
	e('...elt',       'do_dotsElt',      0, 201,  1, FN, PREC, 0),
	e('...length',    'do_dotsLength',   0,   1,  0, FN, PREC, 0),
	e('...names',     'do_dotsNames',    0,   1,  0, FN, PREC, 0),
	e('length',       'do_length',       0,   1,  1, FN, PREC, 0),
	e('length<-',     'do_lengthgets',   0,   1,  2, FN, Precedence.Left, 1),
	e('c',            'do_c',            0,   1, -1, FN, PREC, 0),
	e('oldClass',     'do_class',        0,   1,  1, FN, PREC, 0),
	e('oldClass<-',   'do_classgets',    0,   1,  2, FN, Precedence.Left, 1),
	e('class',        'R_do_data_class', 0,   1,  1, FN, PREC, 0),
	e('.cache_class', 'R_do_data_class', 1,   1,  2, FN, PREC, 0),
	e('.class2',      'R_do_data_class', 2,   1,  1, FN, PREC, 0),
	e('class<-',      'R_do_set_class',  0,   1,  2, FN, PREC, 0),
	e('unclass',      'do_unclass',      0,   1,  1, FN, PREC, 0),
	e('names',        'do_names',        0,   1,  1, FN, PREC, 0),
	e('names<-',      'do_namesgets',    0,   1,  2, FN, Precedence.Left, 1),
	e('dimnames',     'do_dimnames',     0,   1,  1, FN, PREC, 0),
	e('dimnames<-',   'do_dimnamesgets', 0,   1,  2, FN, Precedence.Left, 1),
	e('dim',          'do_dim',          0,   1,  1, FN, PREC, 0),
	e('dim<-',        'do_dimgets',      0,   1,  2, FN, Precedence.Left, 1),
	e('attributes',   'do_attributes',   0,   1,  1, FN, PREC, 0),
	e('attributes<-', 'do_attributesgets', 0, 1,  2, FN, Precedence.Left, 1),
	e('attr',         'do_attr',         0,   1, -1, FN, PREC, 0),
	e('attr<-',       'do_attrgets',     0,   1,  3, FN, Precedence.Left, 1),
	e('@<-',          'do_attrgets',     1,   0,  3, PPKind.SubAss, Precedence.Left, 1),
	e('levels<-',     'do_levelsgets',   0,   1,  2, FN, Precedence.Left, 1),
	e('vector',       'do_makevector',   0,  11,  2, FN, PREC, 0),
	e('complex',      'do_complex',      0,  11,  3, FN, PREC, 0),
	e('matrix',       'do_matrix',       0,  11,  7, FN, PREC, 0),
	e('array',        'do_array',        0,  11,  3, FN, PREC, 0),
	e('diag',         'do_diag',         0,  11,  3, FN, PREC, 0),
	e('backsolve',    'do_backsolve',     0,  11,  5, FN, PREC, 0),
	e('max.col',      'do_maxcol',       0,  11,  2, FN, PREC, 0),
	e('row',          'do_rowscols',     1,  11,  1, FN, PREC, 0),
	e('col',          'do_rowscols',     2,  11,  1, FN, PREC, 0),
	e('unlist',       'do_unlist',       0,  11,  3, FN, PREC, 0),
	e('cbind',        'do_bind',         1,  10, -1, FN, PREC, 0),
	e('rbind',        'do_bind',         2,  10, -1, FN, PREC, 0),
	e('drop',         'do_drop',         0,  11,  1, FN, PREC, 0),
	e('all.names',    'do_allnames',     0,  11,  4, FN, PREC, 0),
	e('comment',      'do_comment',      0,  11,  1, FN, PREC, 0),
	e('comment<-',    'do_commentgets',  0,  11,  2, FN, Precedence.Left, 1),
	e('get',          'do_get',          1,  11,  4, FN, PREC, 0),
	e('get0',         'do_get',          2,  11,  5, FN, PREC, 0),
	e('mget',         'do_mget',         1,  11,  5, FN, PREC, 0),
	e('exists',       'do_get',          0,  11,  4, FN, PREC, 0),
	e('assign',       'do_assign',       0, 111,  4, FN, PREC, 0),
	e('list2env',     'do_list2env',     0,  11,  2, FN, PREC, 0),
	e('remove',       'do_remove',       0, 111,  3, FN, PREC, 0),
	e('duplicated',   'do_duplicated',   0,  11,  4, FN, PREC, 0),
	e('unique',       'do_duplicated',   1,  11,  4, FN, PREC, 0),
	e('anyDuplicated', 'do_duplicated',   2,  11,  3, FN, PREC, 0),
	e('anyNA',        'do_anyNA',        0,   1, -1, FN, PREC, 0),
	e('which',        'do_which',        0,  11,  1, FN, PREC, 0),
	e('which.min',    'do_first_min',    0,  11,  1, FN, PREC, 0),
	e('pmin',         'do_pmin',         0,  11, -1, FN, PREC, 0),
	e('pmax',         'do_pmin',         1,  11, -1, FN, PREC, 0),
	e('which.max',    'do_first_min',    1,  11,  1, FN, PREC, 0),
	e('match',        'do_match',        0,  11,  4, FN, PREC, 0),
	e('pmatch',       'do_pmatch',       0,  11,  4, FN, PREC, 0),
	e('charmatch',    'do_charmatch',    0,  11,  3, FN, PREC, 0),
	e('match.call',   'do_matchcall',    0,  11,  4, FN, PREC, 0),
	e('crossprod',    'do_matprod',      1,   1,  1, FN, PREC, 0),
	e('tcrossprod',   'do_matprod',      2,   1,  1, FN, PREC, 0),
	e('asplit',       'do_asplit',       0,  11,  8, FN, PREC, 0),
	e('lengths',      'do_lengths',      0,  11,  2, FN, PREC, 0),
	e('sequence',     'do_sequence',     0,  11,  4, FN, PREC, 0),
	e('vhash',        'do_vhash',        0,  11, -1, FN, PREC, 0),
	e('attach',       'do_attach',       0, 111,  3, FN, PREC, 0),
	e('detach',       'do_detach',       0, 111,  1, FN, PREC, 0),
	e('search',       'do_search',       0,  11,  0, FN, PREC, 0),
	e('setFileTime',  'do_setFileTime',  0, 111,  2, FN, PREC, 0),

	/* -- Math (primitives) -- */
	e('round',   'do_Math2',   10001, 0, -1, FN, PREC, 0),
	e('signif',  'do_Math2',   10004, 0, -1, FN, PREC, 0),
	e('log',     'do_log',     10003, 0, -1, FN, PREC, 0),
	e('log10',   'do_log1arg', 10010, 1,  1, FN, PREC, 0),
	e('log2',    'do_log1arg', 10002, 1,  1, FN, PREC, 0),
	e('abs',     'do_abs',         6, 1,  1, FN, PREC, 0),
	e('floor',   'do_math1',       1, 1,  1, FN, PREC, 0),
	e('ceiling', 'do_math1',       2, 1,  1, FN, PREC, 0),
	e('sqrt',    'do_math1',       3, 1,  1, FN, PREC, 0),
	e('sign',    'do_math1',       4, 1,  1, FN, PREC, 0),
	e('trunc',   'do_trunc',       5, 1, -1, FN, PREC, 0),
	e('exp',     'do_math1',      10, 1,  1, FN, PREC, 0),
	e('expm1',   'do_math1',      11, 1,  1, FN, PREC, 0),
	e('log1p',   'do_math1',      12, 1,  1, FN, PREC, 0),
	e('cos',     'do_math1',      20, 1,  1, FN, PREC, 0),
	e('sin',     'do_math1',      21, 1,  1, FN, PREC, 0),
	e('tan',     'do_math1',      22, 1,  1, FN, PREC, 0),
	e('acos',    'do_math1',      23, 1,  1, FN, PREC, 0),
	e('asin',    'do_math1',      24, 1,  1, FN, PREC, 0),
	e('atan',    'do_math1',      25, 1,  1, FN, PREC, 0),
	e('cosh',    'do_math1',      30, 1,  1, FN, PREC, 0),
	e('sinh',    'do_math1',      31, 1,  1, FN, PREC, 0),
	e('tanh',    'do_math1',      32, 1,  1, FN, PREC, 0),
	e('acosh',   'do_math1',      33, 1,  1, FN, PREC, 0),
	e('asinh',   'do_math1',      34, 1,  1, FN, PREC, 0),
	e('atanh',   'do_math1',      35, 1,  1, FN, PREC, 0),
	e('lgamma',  'do_math1',      40, 1,  1, FN, PREC, 0),
	e('gamma',   'do_math1',      41, 1,  1, FN, PREC, 0),
	e('digamma', 'do_math1',      42, 1,  1, FN, PREC, 0),
	e('trigamma', 'do_math1',      43, 1,  1, FN, PREC, 0),
	e('cospi',   'do_math1',      47, 1,  1, FN, PREC, 0),
	e('sinpi',   'do_math1',      48, 1,  1, FN, PREC, 0),
	e('tanpi',   'do_math1',      49, 1,  1, FN, PREC, 0),

	/* -- Math 2 -- */
	e('atan2',     'do_math2',  0, 11, 2, FN, PREC, 0), e('lbeta',     'do_math2',  2, 11, 2, FN, PREC, 0),
	e('beta',      'do_math2',  3, 11, 2, FN, PREC, 0), e('lchoose',   'do_math2',  4, 11, 2, FN, PREC, 0),
	e('choose',    'do_math2',  5, 11, 2, FN, PREC, 0), e('dchisq',    'do_math2',  6, 11, 3, FN, PREC, 0),
	e('pchisq',    'do_math2',  7, 11, 4, FN, PREC, 0), e('qchisq',    'do_math2',  8, 11, 4, FN, PREC, 0),
	e('dexp',      'do_math2',  9, 11, 3, FN, PREC, 0), e('pexp',      'do_math2', 10, 11, 4, FN, PREC, 0),
	e('qexp',      'do_math2', 11, 11, 4, FN, PREC, 0), e('dgeom',     'do_math2', 12, 11, 3, FN, PREC, 0),
	e('pgeom',     'do_math2', 13, 11, 4, FN, PREC, 0), e('qgeom',     'do_math2', 14, 11, 4, FN, PREC, 0),
	e('dpois',     'do_math2', 15, 11, 3, FN, PREC, 0), e('ppois',     'do_math2', 16, 11, 4, FN, PREC, 0),
	e('qpois',     'do_math2', 17, 11, 4, FN, PREC, 0), e('dt',        'do_math2', 18, 11, 3, FN, PREC, 0),
	e('pt',        'do_math2', 19, 11, 4, FN, PREC, 0), e('qt',        'do_math2', 20, 11, 4, FN, PREC, 0),
	e('dsignrank', 'do_math2', 21, 11, 3, FN, PREC, 0), e('psignrank', 'do_math2', 22, 11, 4, FN, PREC, 0),
	e('qsignrank', 'do_math2', 23, 11, 4, FN, PREC, 0), e('besselJ',   'do_math2', 24, 11, 2, FN, PREC, 0),
	e('besselY',   'do_math2', 25, 11, 2, FN, PREC, 0), e('psigamma',  'do_math2', 26, 11, 2, FN, PREC, 0),

	/* -- Complex math -- */
	e('Re',   'do_cmathfuns', 1, 1, 1, FN, PREC, 0), e('Im',   'do_cmathfuns', 2, 1, 1, FN, PREC, 0),
	e('Mod',  'do_cmathfuns', 3, 1, 1, FN, PREC, 0), e('Arg',  'do_cmathfuns', 4, 1, 1, FN, PREC, 0),
	e('Conj', 'do_cmathfuns', 5, 1, 1, FN, PREC, 0),

	/* -- Math 3 -- */
	e('dbeta',      'do_math3',  1, 11, 4, FN, PREC, 0), e('pbeta',      'do_math3',  2, 11, 5, FN, PREC, 0),
	e('qbeta',      'do_math3',  3, 11, 5, FN, PREC, 0), e('dbinom',     'do_math3',  4, 11, 4, FN, PREC, 0),
	e('pbinom',     'do_math3',  5, 11, 5, FN, PREC, 0), e('qbinom',     'do_math3',  6, 11, 5, FN, PREC, 0),
	e('dcauchy',    'do_math3',  7, 11, 4, FN, PREC, 0), e('pcauchy',    'do_math3',  8, 11, 5, FN, PREC, 0),
	e('qcauchy',    'do_math3',  9, 11, 5, FN, PREC, 0), e('df',         'do_math3', 10, 11, 4, FN, PREC, 0),
	e('pf',         'do_math3', 11, 11, 5, FN, PREC, 0), e('qf',         'do_math3', 12, 11, 5, FN, PREC, 0),
	e('dgamma',     'do_math3', 13, 11, 4, FN, PREC, 0), e('pgamma',     'do_math3', 14, 11, 5, FN, PREC, 0),
	e('qgamma',     'do_math3', 15, 11, 5, FN, PREC, 0), e('dlnorm',     'do_math3', 16, 11, 4, FN, PREC, 0),
	e('plnorm',     'do_math3', 17, 11, 5, FN, PREC, 0), e('qlnorm',     'do_math3', 18, 11, 5, FN, PREC, 0),
	e('dlogis',     'do_math3', 19, 11, 4, FN, PREC, 0), e('plogis',     'do_math3', 20, 11, 5, FN, PREC, 0),
	e('qlogis',     'do_math3', 21, 11, 5, FN, PREC, 0), e('dnbinom',    'do_math3', 22, 11, 4, FN, PREC, 0),
	e('pnbinom',    'do_math3', 23, 11, 5, FN, PREC, 0), e('qnbinom',    'do_math3', 24, 11, 5, FN, PREC, 0),
	e('dnorm',      'do_math3', 25, 11, 4, FN, PREC, 0), e('pnorm',      'do_math3', 26, 11, 5, FN, PREC, 0),
	e('qnorm',      'do_math3', 27, 11, 5, FN, PREC, 0), e('dunif',      'do_math3', 28, 11, 4, FN, PREC, 0),
	e('punif',      'do_math3', 29, 11, 5, FN, PREC, 0), e('qunif',      'do_math3', 30, 11, 5, FN, PREC, 0),
	e('dweibull',   'do_math3', 31, 11, 4, FN, PREC, 0), e('pweibull',   'do_math3', 32, 11, 5, FN, PREC, 0),
	e('qweibull',   'do_math3', 33, 11, 5, FN, PREC, 0), e('dnchisq',    'do_math3', 34, 11, 4, FN, PREC, 0),
	e('pnchisq',    'do_math3', 35, 11, 5, FN, PREC, 0), e('qnchisq',    'do_math3', 36, 11, 5, FN, PREC, 0),
	e('dnt',        'do_math3', 37, 11, 4, FN, PREC, 0), e('pnt',        'do_math3', 38, 11, 5, FN, PREC, 0),
	e('qnt',        'do_math3', 39, 11, 5, FN, PREC, 0), e('dwilcox',    'do_math3', 40, 11, 4, FN, PREC, 0),
	e('pwilcox',    'do_math3', 41, 11, 5, FN, PREC, 0), e('qwilcox',    'do_math3', 42, 11, 5, FN, PREC, 0),
	e('besselI',    'do_math3', 43, 11, 3, FN, PREC, 0), e('besselK',    'do_math3', 44, 11, 3, FN, PREC, 0),
	e('dnbinom_mu', 'do_math3', 45, 11, 4, FN, PREC, 0), e('pnbinom_mu', 'do_math3', 46, 11, 5, FN, PREC, 0),
	e('qnbinom_mu', 'do_math3', 47, 11, 5, FN, PREC, 0),

	/* -- Math 4 -- */
	e('dhyper', 'do_math4',  1, 11, 5, FN, PREC, 0), e('phyper', 'do_math4',  2, 11, 6, FN, PREC, 0),
	e('qhyper', 'do_math4',  3, 11, 6, FN, PREC, 0), e('dnbeta', 'do_math4',  4, 11, 5, FN, PREC, 0),
	e('pnbeta', 'do_math4',  5, 11, 6, FN, PREC, 0), e('qnbeta', 'do_math4',  6, 11, 6, FN, PREC, 0),
	e('dnf',    'do_math4',  7, 11, 5, FN, PREC, 0), e('pnf',    'do_math4',  8, 11, 6, FN, PREC, 0),
	e('qnf',    'do_math4',  9, 11, 6, FN, PREC, 0), e('dtukey', 'do_math4', 10, 11, 5, FN, PREC, 0),
	e('ptukey', 'do_math4', 11, 11, 6, FN, PREC, 0), e('qtukey', 'do_math4', 12, 11, 6, FN, PREC, 0),

	/* -- Random Numbers -- */
	e('rchisq',     'do_random1',  0, 11, 2, FN, PREC, 0), e('rexp',      'do_random1',  1, 11, 2, FN, PREC, 0),
	e('rgeom',      'do_random1',  2, 11, 2, FN, PREC, 0), e('rpois',     'do_random1',  3, 11, 2, FN, PREC, 0),
	e('rt',         'do_random1',  4, 11, 2, FN, PREC, 0), e('rsignrank', 'do_random1',  5, 11, 2, FN, PREC, 0),
	e('rbeta',      'do_random2',  0, 11, 3, FN, PREC, 0), e('rbinom',    'do_random2',  1, 11, 3, FN, PREC, 0),
	e('rcauchy',    'do_random2',  2, 11, 3, FN, PREC, 0), e('rf',        'do_random2',  3, 11, 3, FN, PREC, 0),
	e('rgamma',     'do_random2',  4, 11, 3, FN, PREC, 0), e('rlnorm',    'do_random2',  5, 11, 3, FN, PREC, 0),
	e('rlogis',     'do_random2',  6, 11, 3, FN, PREC, 0), e('rnbinom',   'do_random2',  7, 11, 3, FN, PREC, 0),
	e('rnbinom_mu', 'do_random2', 13, 11, 3, FN, PREC, 0), e('rnchisq',   'do_random2', 12, 11, 3, FN, PREC, 0),
	e('rnorm',      'do_random2',  8, 11, 3, FN, PREC, 0), e('runif',     'do_random2',  9, 11, 3, FN, PREC, 0),
	e('rweibull',   'do_random2', 10, 11, 3, FN, PREC, 0), e('rwilcox',   'do_random2', 11, 11, 3, FN, PREC, 0),
	e('rhyper',     'do_random3',  0, 11, 4, FN, PREC, 0), e('sample',    'do_sample',   0, 11, 4, FN, PREC, 0),
	e('sample2',    'do_sample2',  0, 11, 2, FN, PREC, 0), e('RNGkind',   'do_RNGkind',  0, 11, 3, FN, PREC, 0),
	e('set.seed',   'do_setseed',  0, 111, 4, FN, PREC, 0),

	/* -- Data Summaries -- */
	e('sum',    'do_summary', 0,  1, -1, FN, PREC, 0), e('min',     'do_summary', 2,  1, -1, FN, PREC, 0),
	e('max',    'do_summary', 3,  1, -1, FN, PREC, 0), e('prod',    'do_summary', 4,  1, -1, FN, PREC, 0),
	e('mean',   'do_summary', 1, 11,  1, FN, PREC, 0), e('range',   'do_range',   0,  1, -1, FN, PREC, 0),
	e('cumsum', 'do_cum',     1,  1,  1, FN, PREC, 0), e('cumprod', 'do_cum',     2,  1,  1, FN, PREC, 0),
	e('cummax', 'do_cum',     3,  1,  1, FN, PREC, 0), e('cummin',  'do_cum',     4,  1,  1, FN, PREC, 0),

	/* -- Type Coercion -- */
	e('as.character',      'do_asatomic',          0,  1, -1, FN, PREC, 0),
	e('as.integer',        'do_asatomic',          1,  1, -1, FN, PREC, 0),
	e('as.double',         'do_asatomic',          2,  1, -1, FN, PREC, 0),
	e('as.numeric',        'do_asatomic',          2,  1, -1, FN, PREC, 0),
	e('as.complex',        'do_asatomic',          3,  1, -1, FN, PREC, 0),
	e('as.logical',        'do_asatomic',          4,  1, -1, FN, PREC, 0),
	e('as.raw',            'do_asatomic',          5,  1,  1, FN, PREC, 0),
	e('as.call',           'do_ascall',            0,  1,  1, FN, PREC, 0),
	e('as.environment',    'do_as_environment',    0,  1,  1, FN, PREC, 0),
	e('storage.mode<-',    'do_storage_mode',      0,  1,  2, FN, PREC, 0),
	e('asCharacterFactor', 'do_asCharacterFactor', 0, 11,  1, FN, PREC, 0),
	e('as.vector',         'do_asvector',          0, 11,  2, FN, PREC, 0),
	e('paste',             'do_paste',             0, 11,  4, FN, PREC, 0),
	e('paste0',            'do_paste',             1, 11,  3, FN, PREC, 0),
	e('file.path',         'do_filepath',          0, 11,  2, FN, PREC, 0),
	e('format',            'do_format',            0, 11,  9, FN, PREC, 0),
	e('format.info',       'do_formatinfo',        0, 11,  3, FN, PREC, 0),
	e('cat',               'do_cat',               0, 111, 6, FN, PREC, 0),
	e('do.call',           'do_docall',            0, 211, 3, FN, PREC, 0),
	e('str2lang',          'do_str2lang',          0, 11,  1, FN, PREC, 0),
	e('str2expression',    'do_str2lang',          1, 11,  1, FN, PREC, 0),

	/* -- String Manipulation -- */
	e('substr',      'do_substr',     1, 11, 3, FN, PREC, 0), e('startsWith',   'do_startsWith',   0, 11,  2, FN, PREC, 0),
	e('endsWith',    'do_startsWith', 1, 11, 2, FN, PREC, 0), e('substr<-',     'do_substrgets',   1, 11,  4, FN, PREC, 0),
	e('strsplit',    'do_strsplit',   1, 11, 5, FN, PREC, 0), e('abbreviate',   'do_abbrev',       1, 11,  3, FN, PREC, 0),
	e('make.names',  'do_makenames',  0, 11, 2, FN, PREC, 0), e('pcre_config',  'do_pcre_config',  1, 11,  0, FN, PREC, 0),
	e('grep',        'do_grep',       0, 11, 8, FN, PREC, 0), e('grepl',        'do_grep',         1, 11,  8, FN, PREC, 0),
	e('grepRaw',     'do_grepraw',    0, 11, 8, FN, PREC, 0), e('sub',          'do_gsub',         0, 11,  7, FN, PREC, 0),
	e('gsub',        'do_gsub',       1, 11, 7, FN, PREC, 0), e('regexpr',      'do_regexpr',      0, 11,  6, FN, PREC, 0),
	e('gregexpr',    'do_regexpr',    1, 11, 6, FN, PREC, 0), e('regexec',      'do_regexec',      1, 11,  5, FN, PREC, 0),
	e('agrep',       'do_agrep',      0, 11, 8, FN, PREC, 0), e('agrepl',       'do_agrep',        1, 11,  8, FN, PREC, 0),
	e('adist',       'do_adist',      1, 11, 8, FN, PREC, 0), e('aregexec',     'do_aregexec',     1, 11,  7, FN, PREC, 0),
	e('tolower',     'do_tolower',    0, 11, 1, FN, PREC, 0), e('toupper',      'do_tolower',      1, 11,  1, FN, PREC, 0),
	e('chartr',      'do_chartr',     1, 11, 3, FN, PREC, 0), e('sprintf',      'do_sprintf',      1, 11, -1, FN, PREC, 0),
	e('make.unique', 'do_makeunique', 0, 11, 2, FN, PREC, 0), e('charToRaw',    'do_charToRaw',    1, 11,  1, FN, PREC, 0),
	e('rawToChar',   'do_rawToChar',  1, 11, 2, FN, PREC, 0), e('rawShift',     'do_rawShift',     1, 11,  2, FN, PREC, 0),
	e('intToBits',   'do_intToBits',  1, 11, 1, FN, PREC, 0), e('numToBits',    'do_numToBits',    1, 11,  1, FN, PREC, 0),
	e('numToInts',   'do_numToInts',  1, 11, 1, FN, PREC, 0), e('rawToBits',    'do_rawToBits',    1, 11,  1, FN, PREC, 0),
	e('packBits',    'do_packBits',   1, 11, 2, FN, PREC, 0), e('utf8ToInt',    'do_utf8ToInt',    1, 11,  1, FN, PREC, 0),
	e('intToUtf8',   'do_intToUtf8',  1, 11, 3, FN, PREC, 0), e('validUTF8',    'do_validUTF8',    1, 11,  1, FN, PREC, 0),
	e('validEnc',    'do_validEnc',   1, 11, 1, FN, PREC, 0), e('encodeString', 'do_encodeString', 1, 11,  5, FN, PREC, 0),
	e('iconv',       'do_iconv',      0, 11, 6, FN, PREC, 0), e('strtrim',      'do_strtrim',      0, 11,  2, FN, PREC, 0),
	e('strtoi',      'do_strtoi',     0, 11, 2, FN, PREC, 0), e('strrep',       'do_strrep',       0, 11,  2, FN, PREC, 0),

	/* -- Type Checking -- */
	e('is.null',        'do_is', 'NILSXP',  1, 1, FN, PREC, 0), e('is.logical',    'do_is', 'LGLSXP',  1, 1, FN, PREC, 0),
	e('is.integer',     'do_is', 'INTSXP',  1, 1, FN, PREC, 0), e('is.double',     'do_is', 'REALSXP', 1, 1, FN, PREC, 0),
	e('is.complex',     'do_is', 'CPLXSXP', 1, 1, FN, PREC, 0), e('is.character',  'do_is', 'STRSXP',  1, 1, FN, PREC, 0),
	e('is.symbol',      'do_is', 'SYMSXP',  1, 1, FN, PREC, 0), e('is.name',       'do_is', 'SYMSXP',  1, 1, FN, PREC, 0),
	e('is.environment', 'do_is', 'ENVSXP',  1, 1, FN, PREC, 0), e('is.list',       'do_is', 'VECSXP',  1, 1, FN, PREC, 0),
	e('is.pairlist',    'do_is', 'LISTSXP', 1, 1, FN, PREC, 0), e('is.expression', 'do_is', 'EXPRSXP', 1, 1, FN, PREC, 0),
	e('is.raw',         'do_is', 'RAWSXP',  1, 1, FN, PREC, 0), e('is.object',     'do_is', 50,        1, 1, FN, PREC, 0),
	e('isS4',           'do_is', 51,        1, 1, FN, PREC, 0), e('is.numeric',    'do_is', 100,       1, 1, FN, PREC, 0),
	e('is.matrix',      'do_is', 101,       1, 1, FN, PREC, 0), e('is.array',      'do_is', 102,       1, 1, FN, PREC, 0),
	e('is.atomic',      'do_is', 200,       1, 1, FN, PREC, 0), e('is.recursive',  'do_is', 201,       1, 1, FN, PREC, 0),
	e('is.call',        'do_is', 300,       1, 1, FN, PREC, 0), e('is.language',   'do_is', 301,       1, 1, FN, PREC, 0),
	e('is.function',    'do_is', 302,       1, 1, FN, PREC, 0), e('is.single',     'do_is', 999,       1, 1, FN, PREC, 0),
	e('str2expression',    'do_str2lang',          1, 11,  1, FN, PREC, 0),
	e('is.na',         'do_isna',       0, 1, 1, FN, PREC, 0), e('is.nan',        'do_isnan',      0, 1, 1, FN, PREC, 0),
	e('is.finite',     'do_isfinite',   0, 1, 1, FN, PREC, 0), e('is.infinite',   'do_isinfinite', 0, 1, 1, FN, PREC, 0),
	e('is.vector',     'do_isvector',   0, 11, 2, FN, PREC, 0),

	/* -- Miscellaneous (primitives) -- */
	e('proc.time',   'do_proctime',    0,   1,  0, FN, PREC, 0), e('gc.time',       'do_gctime',     0,   1, -1, FN, PREC, 0),
	e('withVisible', 'do_withVisible', 1,  10,  1, FN, PREC, 0), e('expression',    'do_expression', 1,   0, -1, FN, PREC, 0),
	e('interactive', 'do_interactive', 0,   1,  0, FN, PREC, 0), e('invisible',     'do_invisible',  0, 101,  1, FN, PREC, 0),
	e('rep',         'do_rep',         0,   0, -1, FN, PREC, 0), e('rep.int',       'do_rep_int',    0,  11,  2, FN, PREC, 0),
	e('rep_len',     'do_rep_len',     0,  11,  2, FN, PREC, 0), e('seq.int',       'do_seq',        0,   1, -1, FN, PREC, 0),
	e('seq_len',     'do_seq_len',     0,   1,  1, FN, PREC, 0), e('seq_along',     'do_seq_along',  0,   1,  1, FN, PREC, 0),
	e('list',        'do_makelist',    1,   1, -1, FN, PREC, 0), e('xtfrm',         'do_xtfrm',      0,   1,  1, FN, PREC, 0),
	e('enc2native',  'do_enc2',        0,   1,  1, FN, PREC, 0), e('enc2utf8',      'do_enc2',       1,   1,  1, FN, PREC, 0),
	e('emptyenv',    'do_emptyenv',    0,   1,  0, FN, PREC, 0), e('baseenv',       'do_baseenv',    0,   1,  0, FN, PREC, 0),
	e('globalenv',   'do_globalenv',   0,   1,  0, FN, PREC, 0), e('environment<-', 'do_envirgets', 0,   1,  2, FN, Precedence.Left, 1),
	e('pos.to.env',  'do_pos2env',     0,   1,  1, FN, PREC, 0),

	/* -- Foreign interface -- */
	e('.C',                 'do_dotCode',    0,   1, -1, PPKind.Foreign, PREC, 0),
	e('.Fortran',           'do_dotCode',    1,   1, -1, PPKind.Foreign, PREC, 0),
	e('.External',          'do_External',   0,   1, -1, PPKind.Foreign, PREC, 0),
	e('.External2',         'do_External',   1, 201, -1, PPKind.Foreign, PREC, 0),
	e('.Call',              'do_dotcall',    0,   1, -1, PPKind.Foreign, PREC, 0),
	e('.External.graphics', 'do_Externalgr', 0,   1, -1, PPKind.Foreign, PREC, 0),
	e('.Call.graphics',     'do_dotcallgr',  0,   1, -1, PPKind.Foreign, PREC, 0),

	/* -- .Internal apply family -- */
	e('eapply', 'do_eapply', 0, 10, 4, FN, PREC, 0), e('lapply', 'do_lapply', 0, 10, 2, FN, PREC, 0),
	e('vapply', 'do_vapply', 0, 10, 4, FN, PREC, 0), e('mapply', 'do_mapply', 0, 11, 3, FN, PREC, 0),

	/* -- System info -- */
	e('Version',     'do_version',     0, 11, 0, FN, PREC, 0), e('machine',     'do_machine',     0, 11, 0, FN, PREC, 0),
	e('commandArgs', 'do_commandArgs', 0, 11, 0, FN, PREC, 0), e('internalsID', 'do_internalsID', 0, 11, 0, FN, PREC, 0),
	e('system',      'do_system',      0, 211, 4, FN, PREC, 0),

	/* -- Parse / deparse / IO -- */
	e('parse',                 'do_parse',               0, 11,   6, FN, PREC, 0),
	e('save',                  'do_save',                0, 111,  6, FN, PREC, 0),
	e('saveToConn',            'do_saveToConn',          0, 111,  6, FN, PREC, 0),
	e('load',                  'do_load',                0, 111,  2, FN, PREC, 0),
	e('loadFromConn2',         'do_loadFromConn2',       0, 111,  3, FN, PREC, 0),
	e('loadInfoFromConn2',     'do_loadFromConn2',       1,  11,  1, FN, PREC, 0),
	e('serializeToConn',       'do_serializeToConn',     0, 111,  5, FN, PREC, 0),
	e('unserializeFromConn',   'do_unserializeFromConn', 0,  11,  2, FN, PREC, 0),
	e('serializeInfoFromConn', 'do_unserializeFromConn', 1,  11,  1, FN, PREC, 0),
	e('deparse',               'do_deparse',             0,  11,  5, FN, PREC, 0),
	e('dput',                  'do_dput',                0, 111,  3, FN, PREC, 0),
	e('dump',                  'do_dump',                0, 111, 5, FN, PREC, 0),
	e('quit',                  'do_quit',                0, 111,  3, FN, PREC, 0),
	e('readline',              'do_readln',              0,  11,  1, FN, PREC, 0),
	e('print.default',         'do_printdefault',        0, 111,  3, FN, PREC, 0),
	e('prmatrix',              'do_prmatrix',            0, 111,  6, FN, PREC, 0),
	e('gc',                    'do_gc',                  0,  11,  3, FN, PREC, 0),
	e('gcinfo',                'do_gcinfo',              0,  11,  1, FN, PREC, 0),
	e('gctorture',             'do_gctorture',           0, 111,  1, FN, PREC, 0),
	e('gctorture2',            'do_gctorture2',          0,  11,  3, FN, PREC, 0),
	e('memory.profile',        'do_memoryprofile',       0,  11,  0, FN, PREC, 0),
	e('mem.maxVSize',          'do_maxVSize',            0,  11,  1, FN, PREC, 0),
	e('mem.maxNSize',          'do_maxNSize',            0,  11,  1, FN, PREC, 0),
	e('split',                 'do_split',               0,  11,  2, FN, PREC, 0),
	e('is.loaded',             'do_isloaded',            0,  11, -1, PPKind.Foreign, PREC, 0),
	e('recordGraphics',        'do_recordGraphics',      0, 211,  3, PPKind.Foreign, PREC, 0),
	e('dyn.load',              'do_dynload',             0, 111,  4, FN, PREC, 0),
	e('dyn.unload',            'do_dynunload',           0, 111,  1, FN, PREC, 0),
	e('ls',                    'do_ls',                  1,  11,  3, FN, PREC, 0),
	e('typeof',                'do_typeof',              1,  11,  1, FN, PREC, 0),
	e('eval',                  'do_eval',                0, 211,  3, FN, PREC, 0),
	e('Exec',                  'do_tailcall',            0, 200, -1, FN, PREC, 0),
	e('Tailcall',              'do_tailcall',            1, 200, -1, FN, PREC, 0),
	e('returnValue',           'do_returnValue',         0,  11,  1, FN, PREC, 0),
	e('sys.parent',            'do_sys',                 1,  11,  -1, FN, PREC, 0),
	e('sys.call',              'do_sys',                 2,  11, -1, FN, PREC, 0),
	e('sys.frame',             'do_sys',                 3,  11, -1, FN, PREC, 0),
	e('sys.nframe',            'do_sys',                 4,  11, -1, FN, PREC, 0),
	e('sys.calls',             'do_sys',                 5,  11, -1, FN, PREC, 0),
	e('sys.frames',            'do_sys',                 6,  11, -1, FN, PREC, 0),
	e('sys.on.exit',           'do_sys',                 7,  11, -1, FN, PREC, 0),
	e('sys.parents',           'do_sys',                 8,  11, -1, FN, PREC, 0),
	e('sys.function',          'do_sys',                 9,  11, -1, FN, PREC, 0),
	e('traceback',             'do_traceback',           0,  11,  1, FN, PREC, 0),
	e('browserText',           'do_sysbrowser',          1,  11,  1, FN, PREC, 0),
	e('browserCondition',      'do_sysbrowser',          2,  11,  1, FN, PREC, 0),
	e('browserSetDebug',       'do_sysbrowser',          3, 111,  1, FN, PREC, 0),
	e('parent.frame',          'do_parentframe',         0,  11,  1, FN, PREC, 0),
	e('sort',                  'do_sort',                1,  11,  2, FN, PREC, 0),
	e('is.unsorted',           'do_isunsorted',          0,  11,  3, FN, PREC, 0),
	e('sorted_fpass',          'do_sorted_fpass',        0,  11,  3, FN, PREC, 0),
	e('psort',                 'do_psort',               0,  11,  2, FN, PREC, 0),
	e('qsort',                 'do_qsort',               0,  11,  2, FN, PREC, 0),
	e('radixsort',             'do_radixsort',           0,  11, -1, FN, PREC, 0),
	e('order',                 'do_order',               0,  11, -1, FN, PREC, 0),
	e('rank',                  'do_rank',                0,  11,  3, FN, PREC, 0),
	e('scan',                  'do_scan',                0,  11, 19, FN, PREC, 0),
	e('t.default',             'do_transpose',           0,  11,  1, FN, PREC, 0),
	e('aperm',                 'do_aperm',               0,  11,  3, FN, PREC, 0),
	e('builtins',              'do_builtins',            0,  11,  1, FN, PREC, 0),
	e('args',                  'do_args',                0,  11,  1, FN, PREC, 0),
	e('formals',               'do_formals',             0,  11,  1, FN, PREC, 0),
	e('body',                  'do_body',                0,  11,  1, FN, PREC, 0),
	e('bodyCode',              'do_bodyCode',            0,  11,  1, FN, PREC, 0),
	e('environment',           'do_envir',               0,  11,  1, FN, PREC, 0),
	e('environmentName',       'do_envirName',           0,  11,  1, FN, PREC, 0),
	e('env2list',              'do_env2list',            0,  11,  3, FN, PREC, 0),
	e('reg.finalizer',         'do_regFinaliz',          0,  11,  3, FN, PREC, 0),
	e('options',               'do_options',             0, 211, -1, FN, PREC, 0),
	e('getOption',             'do_getOption',           0,  11,  1, FN, PREC, 0),
	e('sink',                  'do_sink',                0, 111,  4, FN, PREC, 0),
	e('sink.number',           'do_sinknumber',          0,  11,  1, FN, PREC, 0),
	e('rapply',                'do_rapply',              0,  11,  5, FN, PREC, 0),
	e('islistfactor',          'do_islistfactor',        0,  11,  2, FN, PREC, 0),
	e('colSums',               'do_colsum',              0,  11,  4, FN, PREC, 0),
	e('colMeans',              'do_colsum',              1,  11,  4, FN, PREC, 0),
	e('rowSums',               'do_colsum',              2,  11,  4, FN, PREC, 0),
	e('rowMeans',              'do_colsum',              3,  11,  4, FN, PREC, 0),
	e('tracemem',              'do_tracemem',            0,   1,  1, FN, PREC, 0),
	e('retracemem',            'do_retracemem',          0, 201, -1, FN, PREC, 0),
	e('untracemem',            'do_untracemem',          0, 101,  1, FN, PREC, 0),
	e('inspect',               'do_inspect',             0, 111, -1, FN, PREC, 0),
	e('address',               'do_address',             0,  11,  1, FN, PREC, 0),
	e('named',                 'do_named',               0,  11,  1, FN, PREC, 0),
	e('refcnt',                'do_refcnt',              0,  11,  1, FN, PREC, 0),
	e('merge',                 'do_merge',               0,  11,  4, FN, PREC, 0),
	e('capabilities',          'do_capabilities',        0,  11,  0, FN, PREC, 0),
	e('capabilitiesX11',       'do_capabilitiesX11',     0,  11,  0, FN, PREC, 0),
	e('new.env',               'do_newenv',              0,  11,  3, FN, PREC, 0),
	e('parent.env',            'do_parentenv',           0,  11,  1, FN, PREC, 0),
	e('parent.env<-',          'do_parentenvgets',       0,  11,  2, FN, Precedence.Left, 1),
	e('topenv',                'do_topenv',              0,  11,  2, FN, PREC, 0),
	e('l10n_info',             'do_l10n_info',           0,  11,  0, FN, PREC, 0),
	e('Cstack_info',           'do_Cstack_info',         0,  11,  0, FN, PREC, 0),
	e('mmap_file',             'do_mmap_file',           0,  11, -1, FN, PREC, 0),
	e('munmap_file',           'do_munmap_file',         0, 111,  1, FN, PREC, 0),
	e('wrap_meta',             'do_wrap_meta',           0,  11,  3, FN, PREC, 0),
	e('tryWrap',               'do_tryWrap',             0,  11,  1, FN, PREC, 0),
	e('altrep_class',          'do_altrep_class',        0,  11,  1, FN, PREC, 0),

	/* -- OS interaction -- */
	e('file.show',      'do_fileshow',   0, 111, 5, FN, PREC, 0), e('file.create',   'do_filecreate',     0,   11, 2, FN, PREC, 0),
	e('file.remove',    'do_fileremove', 0,  11, 1, FN, PREC, 0), e('file.rename',   'do_filerename',     0,   11, 2, FN, PREC, 0),
	e('file.append',    'do_fileappend', 0,  11, 2, FN, PREC, 0), e('file.symlink',  'do_filesymlink',    0,   11, 2, FN, PREC, 0),
	e('file.link',      'do_filelink',   0,  11, 2, FN, PREC, 0), e('file.copy',     'do_filecopy',       0,   11, 6, FN, PREC, 0),
	e('list.files',     'do_listfiles',  0,  11, 9, FN, PREC, 0), e('list.dirs',     'do_listdirs',       0,   11, 3, FN, PREC, 0),
	e('file.exists',    'do_fileexists', 0,  11, 1, FN, PREC, 0), e('file.choose',   'do_filechoose',     0,   11, 1, FN, PREC, 0),
	e('file.info',      'do_fileinfo',   0,  11, 2, FN, PREC, 0), e('file.access',   'do_fileaccess',     0,   11, 2, FN, PREC, 0),
	e('dir.exists',     'do_direxists',  0,  11, 1, FN, PREC, 0), e('dir.create',    'do_dircreate',      0,  111, 4, FN, PREC, 0),
	e('tempfile',       'do_tempfile',   0,  11, 3, FN, PREC, 0), e('tempdir',       'do_tempdir',        0,   11, 1, FN, PREC, 0),
	e('R.home',         'do_Rhome',      0,  11, 0, FN, PREC, 0), e('date',          'do_date',           0,   11, 0, FN, PREC, 0),
	e('Sys.getenv',     'do_getenv',     0,  11, 2, FN, PREC, 0), e('Sys.setenv',    'do_setenv',         0,  111, 2, FN, PREC, 0),
	e('Sys.unsetenv',   'do_unsetenv',   0, 111, 1, FN, PREC, 0), e('getwd',         'do_getwd',          0,   11, 0, FN, PREC, 0),
	e('setwd',          'do_setwd',      0, 111, 1, FN, PREC, 0), e('basename',      'do_basename',       0,   11, 1, FN, PREC, 0),
	e('dirname',        'do_dirname',    0,  11, 1, FN, PREC, 0), e('Sys.chmod',     'do_syschmod',       0,  111, 3, FN, PREC, 0),
	e('Sys.umask',      'do_sysumask',   0, 211, 1, FN, PREC, 0), e('Sys.readlink',  'do_readlink',       0,   11, 1, FN, PREC, 0),
	e('Sys.info',       'do_sysinfo',    0,  11, 0, FN, PREC, 0), e('Sys.sleep',     'do_syssleep',       0,  111, 1, FN, PREC, 0),
	e('Sys.getlocale',  'do_getlocale',  0,  11, 1, FN, PREC, 0), e('Sys.setlocale', 'do_setlocale',      0,   11, 2, FN, PREC, 0),
	e('Sys.localeconv', 'do_localeconv', 0,  11, 0, FN, PREC, 0), e('path.expand',   'do_pathexpand',     0,   11, 1, FN, PREC, 0),
	e('Sys.getpid',     'do_sysgetpid',  0,  11, 0, FN, PREC, 0), e('normalizePath',  'do_normalizepath',  0,   11, 3, FN, PREC, 0),
	e('Sys.glob',       'do_glob',       0,  11, 2, FN, PREC, 0), e('unlink',        'do_unlink',         0,  111, 4, FN, PREC, 0),

	/* -- Complex -- */
	e('polyroot', 'do_polyroot', 0, 11, 1, FN, PREC, 0),

	/* -- Objects / S3 -- */
	e('inherits',        'do_inherits',        0,  11,  3, FN, PREC, 0),
	e('UseMethod',       'do_usemethod',       0, 200, -1, FN, PREC, 0),
	e('NextMethod',      'do_nextmethod',      0, 210, -1, FN, PREC, 0),
	e('standardGeneric', 'do_standardGeneric', 0, 201, -1, FN, PREC, 0),

	/* -- Date-time -- */
	e('Sys.time',              'do_systime',               0,  11, 0, FN, PREC, 0),
	e('as.POSIXct',            'do_asPOSIXct',             0,  11, 2, FN, PREC, 0),
	e('as.POSIXlt',            'do_asPOSIXlt',             0,  11, 2, FN, PREC, 0),
	e('format.POSIXlt',        'do_formatPOSIXlt',         0,  11, 4, FN, PREC, 0),
	e('strptime',              'do_strptime',              0,  11, 3, FN, PREC, 0),
	e('Date2POSIXlt',          'do_D2POSIXlt',             0,  11, 2, FN, PREC, 0),
	e('POSIXlt2Date',          'do_POSIXlt2D',             0,  11, 1, FN, PREC, 0),
	e('balancePOSIXlt',        'do_balancePOSIXlt',        0,  11, 3, FN, PREC, 0),
	e('unCfillPOSIXlt',        'do_balancePOSIXlt',        1,   1, 1, FN, PREC, 0),
	e('compareNumericVersion', 'do_compareNumericVersion', 0,  11, 2, FN, PREC, 0),

	/* -- Bytecode compiler -- */
	e('mkCode',               'do_mkcode',              0, 11, 2, FN, PREC, 0), e('bcClose',     'do_bcclose',  0, 11, 3, FN, PREC, 0),
	e('is.builtin.internal',  'do_is_builtin_internal', 0, 11, 1, FN, PREC, 0),
	e('disassemble',          'do_disassemble',         0, 11, 1, FN, PREC, 0), e('bcVersion',   'do_bcversion', 0, 11, 0, FN, PREC, 0),
	e('load.from.file',       'do_loadfile',            0, 11,  1, FN, PREC, 0), e('save.to.file', 'do_savefile', 0, 11, 4, FN, PREC, 0),
	e('growconst',            'do_growconst',           0, 11,  1, FN, PREC, 0), e('putconst',    'do_putconst', 0, 11, 3, FN, PREC, 0),
	e('getconst',             'do_getconst',            0, 11,  2, FN, PREC, 0), e('enableJIT',   'do_enablejit', 0, 11, 1, FN, PREC, 0),
	e('compilePKGS',          'do_compilepkgs',         0, 11, 1, FN, PREC, 0),
	e('setNumMathThreads',    'do_setnumthreads',       0, 11, 1, FN, PREC, 0),
	e('setMaxNumMathThreads', 'do_setmaxnumthreads',    0, 11, 1, FN, PREC, 0),

	/* -- Connections -- */
	e('stdin',          'do_stdin',    0,  11, 0, FN, PREC, 0), e('stdout',         'do_stdout',   0,  11, 0, FN, PREC, 0),
	e('stderr',         'do_stderr',   0,  11, 0, FN, PREC, 0), e('isatty',         'do_isatty',   0,  11, 1, FN, PREC, 0),
	e('readLines',      'do_readLines', 0,  11, 6, FN, PREC, 0), e('writeLines',     'do_writelines', 0, 111, 4, FN, PREC, 0),
	e('readBin',        'do_readbin',  0,  11, 6, FN, PREC, 0), e('writeBin',       'do_writebin', 0, 211, 5, FN, PREC, 0),
	e('readChar',       'do_readchar', 0,  11, 3, FN, PREC, 0), e('writeChar',      'do_writechar', 0, 211, 5, FN, PREC, 0),
	e('open',           'do_open',     0, 111, 3, FN, PREC, 0), e('isOpen',         'do_isopen',   0,  11, 2, FN, PREC, 0),
	e('isIncomplete',   'do_isincomplete', 0, 11, 1, FN, PREC, 0), e('isSeekable',    'do_isseekable', 0, 11, 1, FN, PREC, 0),
	e('close',          'do_close',    0, 111, 2, FN, PREC, 0), e('flush',          'do_flush',    0, 111, 1, FN, PREC, 0),
	e('file',           'do_url',      1,  11, 6, FN, PREC, 0), e('url',            'do_url',      0,  11, 6, FN, PREC, 0),
	e('pipe',           'do_pipe',     0,  11, 3, FN, PREC, 0), e('fifo',           'do_fifo',     0,  11, 4, FN, PREC, 0),
	e('gzfile',         'do_gzfile',   0,  11, 4, FN, PREC, 0), e('bzfile',         'do_gzfile',   1,  11, 4, FN, PREC, 0),
	e('xzfile',         'do_gzfile',   2,  11, 4, FN, PREC, 0), e('zstdfile',       'do_gzfile',   3,  11, 4, FN, PREC, 0),
	e('unz',            'do_unz',      0,  11, 3, FN, PREC, 0), e('seek',           'do_seek',     0,  11, 4, FN, PREC, 0),
	e('truncate',       'do_truncate', 0,  11, 1, FN, PREC, 0), e('pushBack',       'do_pushback', 0, 111, 4, FN, PREC, 0),
	e('clearPushBack',  'do_clearpushback', 0, 111, 1, FN, PREC, 0), e('pushBackLength', 'do_pushbacklength', 0, 11, 1, FN, PREC, 0),
	e('rawConnection',  'do_rawconnection', 0, 11, 3, FN, PREC, 0), e('rawConnectionValue', 'do_rawconvalue', 0, 11, 1, FN, PREC, 0),
	e('textConnection', 'do_textconnection', 0, 11, 5, FN, PREC, 0), e('textConnectionValue', 'do_textconvalue', 0, 11, 1, FN, PREC, 0),
	e('socketConnection', 'do_sockconn', 0, 11, 8, FN, PREC, 0), e('socketAccept',   'do_sockconn', 1,  11, 6, FN, PREC, 0),
	e('sockSelect',     'do_sockselect', 0, 11, 3, FN, PREC, 0), e('serverSocket',   'do_serversocket', 0, 11, 1, FN, PREC, 0),
	e('socketTimeout',  'do_socktimeout', 0, 11, 2, FN, PREC, 0), e('getConnection',  'do_getconnection', 0, 11, 1, FN, PREC, 0),
	e('getAllConnections', 'do_getallconnections', 0, 11, 0, FN, PREC, 0),
	e('summary.connection', 'do_sumconnection', 0, 11, 1, FN, PREC, 0),
	e('gzcon',          'do_gzcon',    0,  11, 4, FN, PREC, 0),
	e('memCompress',    'do_memCompress',  0, 11, 2, FN, PREC, 0),
	e('memDecompress',  'do_memDecompress', 0, 11, 2, FN, PREC, 0),
	e('readDCF',        'do_readDCF',  0,  11, 3, FN, PREC, 0),

	/* -- Namespace / environment locking -- */
	e('lockEnvironment',      'do_lockEnv',      0, 111, 2, FN, PREC, 0),
	e('environmentIsLocked',  'do_envIsLocked',  0,  11, 1, FN, PREC, 0),
	e('lockBinding',          'do_lockBnd',      0, 111, 2, FN, PREC, 0),
	e('unlockBinding',        'do_lockBnd',      1, 111, 2, FN, PREC, 0),
	e('bindingIsLocked',      'do_bndIsLocked',  0,  11, 2, FN, PREC, 0),
	e('makeActiveBinding',    'do_mkActiveBnd',  0, 111, 3, FN, PREC, 0),
	e('bindingIsActive',      'do_bndIsActive',  0,  11, 2, FN, PREC, 0),
	e('activeBindingFunction', 'do_activeBndFun', 0,  11, 2, FN, PREC, 0),
	e('mkUnbound',            'do_mkUnbound',    0, 111, 1, FN, PREC, 0),
	e('isNamespaceEnv',       'do_isNSEnv',      0,  11, 1, FN, PREC, 0),
	e('registerNamespace',    'do_regNS',        0,  11, 2, FN, PREC, 0),
	e('unregisterNamespace',  'do_unregNS',      0,  11, 1, FN, PREC, 0),
	e('getRegisteredNamespace', 'do_getRegNS',    0,  11, 1, FN, PREC, 0),
	e('isRegisteredNamespace', 'do_getRegNS',     1,  11, 1, FN, PREC, 0),
	e('getNamespaceRegistry', 'do_getNSRegistry', 0,  11, 0, FN, PREC, 0),
	e('importIntoEnv',        'do_importIntoEnv', 0,  11, 4, FN, PREC, 0),
	e('env.profile',          'do_envprofile',   0, 211, 1, FN, PREC, 0),

	/* -- Misc internals -- */
	e('Encoding',        'do_encoding',       0,  11, 1, FN, PREC, 0), e('setEncoding',     'do_setencoding',    0, 11, 2, FN, PREC, 0),
	e('setTimeLimit',    'do_setTimeLimit',   0, 111, 3, FN, PREC, 0), e('setSessionTimeLimit', 'do_setSessionTimeLimit', 0, 111, 2, FN, PREC, 0),
	e('icuSetCollate',   'do_ICUset',         0, 111, -1, FN, PREC, 0), e('icuGetCollate',   'do_ICUget',         0, 11, 1, FN, PREC, 0),
	e('readRenviron',    'do_readEnviron',    0, 111, 1, FN, PREC, 0), e('shortRowNames',   'do_shortRowNames',  0, 11, 2, FN, PREC, 0),
	e('copyDFattr',      'do_copyDFattr',     0,  11, 2, FN, PREC, 0), e('getRegisteredRoutines', 'do_getRegisteredRoutines', 0, 11, 1, FN, PREC, 0),
	e('getLoadedDLLs',   'do_getDllTable',    0,  11, 0, FN, PREC, 0), e('getSymbolInfo',   'do_getSymbolInfo',  0, 11, 3, FN, PREC, 0),
	e('.isMethodsDispatchOn', 'do_S4on',       0,   1, -1, FN, PREC, 0), e('lazyLoadDBfetch', 'do_lazyLoadDBfetch', 0,  1, 4, FN, PREC, 0),
	e('lazyLoadDBflush', 'do_lazyLoadDBflush', 0,  11, 1, FN, PREC, 0), e('getVarsFromFrame', 'do_getVarsFromFrame', 0, 11, 3, FN, PREC, 0),
	e('lazyLoadDBinsertValue', 'do_lazyLoadDBinsertValue', 0, 11, 5, FN, PREC, 0),
	e('bincode',         'do_bincode',        0,  11, 4, FN, PREC, 0), e('tabulate',        'do_tabulate',       0, 11, 2, FN, PREC, 0),
	e('findInterval',    'do_findinterval',   0,  11, 6, FN, PREC, 0), e('pretty',          'do_pretty',         0, 11, 8, FN, PREC, 0),
	e('formatC',         'do_formatC',        0,  11, 7, FN, PREC, 0), e('crc64',           'do_crc64',          0, 11, 1, FN, PREC, 0),
	e('bitwiseAnd',      'do_bitwise',        1,  11, 2, FN, PREC, 0), e('bitwiseNot',      'do_bitwise',        2, 11, 1, FN, PREC, 0),
	e('bitwiseOr',       'do_bitwise',        3,  11, 2, FN, PREC, 0), e('bitwiseXor',      'do_bitwise',        4, 11, 2, FN, PREC, 0),
	e('bitwiseShiftL',   'do_bitwise',        5,  11, 2, FN, PREC, 0), e('bitwiseShiftR',   'do_bitwise',        6, 11, 2, FN, PREC, 0),
	e('serialize',       'do_serialize',      0,  11, 5, FN, PREC, 0), e('serializeb',      'do_serialize',      1, 11, 5, FN, PREC, 0),
	e('unserialize',     'do_serialize',      2,  11, 2, FN, PREC, 0), e('rowsum_matrix',   'do_rowsum',         0, 11, 5, FN, PREC, 0),
	e('rowsum_df',       'do_rowsum',         1,  11, 5, FN, PREC, 0), e('setS4Object',     'do_setS4Object',    0, 11, 3, FN, PREC, 0),
	e('traceOnOff',      'do_traceOnOff',     0,  11, 1, FN, PREC, 0), e('debugOnOff',      'do_traceOnOff',     1, 11, 1, FN, PREC, 0),

	/* -- LAPACK -- */
	e('La_qr_cmplx',  'do_lapack',    0,  11, 1, FN, PREC, 0), e('La_rs',        'do_lapack',   1,  11, 2, FN, PREC, 0),
	e('La_rs_cmplx',  'do_lapack',    2,  11, 2, FN, PREC, 0), e('La_rg',        'do_lapack',   3,  11, 2, FN, PREC, 0),
	e('La_rg_cmplx',  'do_lapack',   41,  11, 2, FN, PREC, 0), e('La_dlange',    'do_lapack',   6,  11, 2, FN, PREC, 0),
	e('La_dgecon',    'do_lapack',    7,  11, 2, FN, PREC, 0), e('La_dtrcon',    'do_lapack',   8,  11, 2, FN, PREC, 0),
	e('La_dtrcon3',   'do_lapack',   81,  11, 3, FN, PREC, 0), e('La_zlange',    'do_lapack',  61,  11, 2, FN, PREC, 0),
	e('La_zgecon',    'do_lapack',    9,  11, 2, FN, PREC, 0), e('La_ztrcon',    'do_lapack',  10,  11, 2, FN, PREC, 0),
	e('La_ztrcon3',   'do_lapack',   13,  11, 3, FN, PREC, 0), e('La_solve_cmplx', 'do_lapack', 11,  11, 3, FN, PREC, 0),
	e('La_solve',     'do_lapack',  100,  11, 3, FN, PREC, 0), e('La_qr',        'do_lapack', 101,  11, 1, FN, PREC, 0),
	e('La_chol',      'do_lapack',  200,  11, 3, FN, PREC, 0), e('La_chol2inv',  'do_lapack', 201,  11, 2, FN, PREC, 0),
	e('qr_coef_real', 'do_lapack',  300,  11, 2, FN, PREC, 0), e('qr_qy_real',   'do_lapack', 301,  11, 3, FN, PREC, 0),
	e('det_ge_real',  'do_lapack',  302,  11, 2, FN, PREC, 0), e('qr_coef_cmplx', 'do_lapack', 303,  11, 2, FN, PREC, 0),
	e('qr_qy_cmplx',  'do_lapack',  304,  11, 3, FN, PREC, 0), e('La_svd',       'do_lapack', 400,  11, 5, FN, PREC, 0),
	e('La_svd_cmplx', 'do_lapack',  401,  11, 5, FN, PREC, 0), e('La_version',   'do_lapack', 1000,  11, 0, FN, PREC, 0),
	e('La_library',   'do_lapack', 1001,  11, 0, FN, PREC, 0),

	/* -- Bytecode profiling -- */
	e('bcprofcounts', 'do_bcprofcounts', 0, 11, 0, FN, PREC, 0),
	e('bcprofstart',  'do_bcprofstart',  0, 11, 0, FN, PREC, 0),
	e('bcprofstop',   'do_bcprofstop',   0, 11, 0, FN, PREC, 0),

	/* -- curl / network -- */
	e('eSoftVersion',    'do_eSoftVersion',    0, 11, 0, FN, PREC, 0), e('curlVersion',    'do_curlVersion',    0, 11, 0, FN, PREC, 0),
	e('curlGetHeaders',  'do_curlGetHeaders',  0, 11, 5, FN, PREC, 0), e('curlDownload',   'do_curlDownload',   0, 11, 6, FN, PREC, 0),
	e('compilerVersion', 'do_compilerVersion', 0, 11, 0, FN, PREC, 0),
];

export const RFunTabOffsets = {
	'if':                     0,            'while':                  0,
	'for':                    0,            'repeat':                 0,
	'break':                  'CTXT_BREAK', 'next':                   'CTXT_NEXT',
	'return':                 0,            'function':               0,
	'<-':                     1,            '=':                      3,
	'<<-':                    2,            '{':                      0,
	'(':                      0,            '.subset':                1,
	'.subset2':               2,            '[':                      1,
	'[[':                     2,            '$':                      3,
	'@':                      0,            '[<-':                    0,
	'[[<-':                   1,            '$<-':                    1,
	'switch':                 0,            'browser':                0,
	'.primTrace':             0,            '.primUntrace':           1,
	'.Internal':              0,            '.Primitive':             0,
	'call':                   0,            'quote':                  0,
	'substitute':             0,            'missing':                1,
	'nargs':                  1,            'on.exit':                0,
	'forceAndCall':           0,            'declare':                0,
	'stop':                   0,            'warning':                0,
	'gettext':                0,            'ngettext':               0,
	'bindtextdomain':         0,            '.addCondHands':          0,
	'.addGlobHands':          0,            '.resetCondHands':        0,
	'.signalCondition':       0,            '.dfltStop':              0,
	'.dfltWarn':              0,            '.addRestart':            0,
	'.getRestart':            0,            '.invokeRestart':         0,
	'.addTryHandlers':        0,            'geterrmessage':          0,
	'seterrmessage':          0,            'printDeferredWarnings':  0,
	'interruptsSuspended':    0,            'as.function.default':    0,
	'debug':                  0,            'undebug':                1,
	'isdebugged':             2,            'debugonce':              3,
	'Recall':                 0,            'delayedAssign':          0,
	'makeLazy':               0,            'identical':              0,
	'C_tryCatchHelper':       0,            'getNamespaceValue':      0,
	'+':                      'PLUSOP',     '-':                      'MINUSOP',
	'*':                      'TIMESOP',    '/':                      'DIVOP',
	'^':                      'POWOP',      '%%':                     'MODOP',
	'%/%':                    'IDIVOP',     '%*%':                    0,
	'==':                     'EQOP',       '!=':                     'NEOP',
	'<':                      'LTOP',       '<=':                     'LEOP',
	'>=':                     'GEOP',       '>':                      'GTOP',
	'&':                      1,            '|':                      2,
	'!':                      3,            '&&':                     1,
	'||':                     2,            ':':                      0,
	'~':                      0,            '::':                     0,
	':::':                    0,            'all':                    1,
	'any':                    2,            '...elt':                 0,
	'...length':              0,            '...names':               0,
	'length':                 0,            'length<-':               0,
	'c':                      0,            'oldClass':               0,
	'oldClass<-':             0,            'class':                  0,
	'.cache_class':           1,            '.class2':                2,
	'class<-':                0,            'unclass':                0,
	'names':                  0,            'names<-':                0,
	'dimnames':               0,            'dimnames<-':             0,
	'dim':                    0,            'dim<-':                  0,
	'attributes':             0,            'attributes<-':           0,
	'attr':                   0,            'attr<-':                 0,
	'@<-':                    1,            'levels<-':               0,
	'vector':                 0,            'complex':                0,
	'matrix':                 0,            'array':                  0,
	'diag':                   0,            'backsolve':              0,
	'max.col':                0,            'row':                    1,
	'col':                    2,            'unlist':                 0,
	'cbind':                  1,            'rbind':                  2,
	'drop':                   0,            'all.names':              0,
	'comment':                0,            'comment<-':              0,
	'get':                    1,            'get0':                   2,
	'mget':                   1,            'exists':                 0,
	'assign':                 0,            'list2env':               0,
	'remove':                 0,            'duplicated':             0,
	'unique':                 1,            'anyDuplicated':          2,
	'anyNA':                  0,            'which':                  0,
	'which.min':              0,            'pmin':                   0,
	'pmax':                   1,            'which.max':              1,
	'match':                  0,            'pmatch':                 0,
	'charmatch':              0,            'match.call':             0,
	'crossprod':              1,            'tcrossprod':             2,
	'asplit':                 0,            'lengths':                0,
	'sequence':               0,            'vhash':                  0,
	'attach':                 0,            'detach':                 0,
	'search':                 0,            'setFileTime':            0,
	'round':                  10001,        'signif':                 10004,
	'log':                    10003,        'log10':                  10010,
	'log2':                   10002,        'abs':                    6,
	'floor':                  1,            'ceiling':                2,
	'sqrt':                   3,            'sign':                   4,
	'trunc':                  5,            'exp':                    10,
	'expm1':                  11,           'log1p':                  12,
	'cos':                    20,           'sin':                    21,
	'tan':                    22,           'acos':                   23,
	'asin':                   24,           'atan':                   25,
	'cosh':                   30,           'sinh':                   31,
	'tanh':                   32,           'acosh':                  33,
	'asinh':                  34,           'atanh':                  35,
	'lgamma':                 40,           'gamma':                  41,
	'digamma':                42,           'trigamma':               43,
	'cospi':                  47,           'sinpi':                  48,
	'tanpi':                  49,           'atan2':                  0,
	'lbeta':                  2,            'beta':                   3,
	'lchoose':                4,            'choose':                 5,
	'dchisq':                 6,            'pchisq':                 7,
	'qchisq':                 8,            'dexp':                   9,
	'pexp':                   10,           'qexp':                   11,
	'dgeom':                  12,           'pgeom':                  13,
	'qgeom':                  14,           'dpois':                  15,
	'ppois':                  16,           'qpois':                  17,
	'dt':                     18,           'pt':                     19,
	'qt':                     20,           'dsignrank':              21,
	'psignrank':              22,           'qsignrank':              23,
	'besselJ':                24,           'besselY':                25,
	'psigamma':               26,           'Re':                     1,
	'Im':                     2,            'Mod':                    3,
	'Arg':                    4,            'Conj':                   5,
	'dbeta':                  1,            'pbeta':                  2,
	'qbeta':                  3,            'dbinom':                 4,
	'pbinom':                 5,            'qbinom':                 6,
	'dcauchy':                7,            'pcauchy':                8,
	'qcauchy':                9,            'df':                     10,
	'pf':                     11,           'qf':                     12,
	'dgamma':                 13,           'pgamma':                 14,
	'qgamma':                 15,           'dlnorm':                 16,
	'plnorm':                 17,           'qlnorm':                 18,
	'dlogis':                 19,           'plogis':                 20,
	'qlogis':                 21,           'dnbinom':                22,
	'pnbinom':                23,           'qnbinom':                24,
	'dnorm':                  25,           'pnorm':                  26,
	'qnorm':                  27,           'dunif':                  28,
	'punif':                  29,           'qunif':                  30,
	'dweibull':               31,           'pweibull':               32,
	'qweibull':               33,           'dnchisq':                34,
	'pnchisq':                35,           'qnchisq':                36,
	'dnt':                    37,           'pnt':                    38,
	'qnt':                    39,           'dwilcox':                40,
	'pwilcox':                41,           'qwilcox':                42,
	'besselI':                43,           'besselK':                44,
	'dnbinom_mu':             45,           'pnbinom_mu':             46,
	'qnbinom_mu':             47,           'dhyper':                 1,
	'phyper':                 2,            'qhyper':                 3,
	'dnbeta':                 4,            'pnbeta':                 5,
	'qnbeta':                 6,            'dnf':                    7,
	'pnf':                    8,            'qnf':                    9,
	'dtukey':                 10,           'ptukey':                 11,
	'qtukey':                 12,           'rchisq':                 0,
	'rexp':                   1,            'rgeom':                  2,
	'rpois':                  3,            'rt':                     4,
	'rsignrank':              5,            'rbeta':                  0,
	'rbinom':                 1,            'rcauchy':                2,
	'rf':                     3,            'rgamma':                 4,
	'rlnorm':                 5,            'rlogis':                 6,
	'rnbinom':                7,            'rnbinom_mu':             13,
	'rnchisq':                12,           'rnorm':                  8,
	'runif':                  9,            'rweibull':               10,
	'rwilcox':                11,           'rhyper':                 0,
	'sample':                 0,            'sample2':                0,
	'RNGkind':                0,            'set.seed':               0,
	'sum':                    0,            'min':                    2,
	'max':                    3,            'prod':                   4,
	'mean':                   1,            'range':                  0,
	'cumsum':                 1,            'cumprod':                2,
	'cummax':                 3,            'cummin':                 4,
	'as.character':           0,            'as.integer':             1,
	'as.double':              2,            'as.numeric':             2,
	'as.complex':             3,            'as.logical':             4,
	'as.raw':                 5,            'as.call':                0,
	'as.environment':         0,            'storage.mode<-':         0,
	'asCharacterFactor':      0,            'as.vector':              0,
	'paste':                  0,            'paste0':                 1,
	'file.path':              0,            'format':                 0,
	'format.info':            0,            'cat':                    0,
	'do.call':                0,            'str2lang':               0,
	'str2expression':         1,            'nchar':                  1,
	'nzchar':                 1,            'substr':                 1,
	'startsWith':             0,            'endsWith':               1,
	'substr<-':               1,            'strsplit':               1,
	'abbreviate':             1,            'make.names':             0,
	'pcre_config':            1,            'grep':                   0,
	'grepl':                  1,            'grepRaw':                0,
	'sub':                    0,            'gsub':                   1,
	'regexpr':                0,            'gregexpr':               1,
	'regexec':                1,            'agrep':                  0,
	'agrepl':                 1,            'adist':                  1,
	'aregexec':               1,            'tolower':                0,
	'toupper':                1,            'chartr':                 1,
	'sprintf':                1,            'make.unique':            0,
	'charToRaw':              1,            'rawToChar':              1,
	'rawShift':               1,            'intToBits':              1,
	'numToBits':              1,            'numToInts':              1,
	'rawToBits':              1,            'packBits':               1,
	'utf8ToInt':              1,            'intToUtf8':              1,
	'validUTF8':              1,            'validEnc':               1,
	'encodeString':           1,            'iconv':                  0,
	'strtrim':                0,            'strtoi':                 0,
	'strrep':                 0,            'is.null':                'NILSXP',
	'is.logical':             'LGLSXP',     'is.integer':             'INTSXP',
	'is.double':              'REALSXP',    'is.complex':             'CPLXSXP',
	'is.character':           'STRSXP',     'is.symbol':              'SYMSXP',
	'is.name':                'SYMSXP',     'is.environment':         'ENVSXP',
	'is.list':                'VECSXP',     'is.pairlist':            'LISTSXP',
	'is.expression':          'EXPRSXP',    'is.raw':                 'RAWSXP',
	'is.object':              50,           'isS4':                   51,
	'is.numeric':             100,          'is.matrix':              101,
	'is.array':               102,          'is.atomic':              200,
	'is.recursive':           201,          'is.call':                300,
	'is.language':            301,          'is.function':            302,
	'is.single':              999,          'is.na':                  0,
	'is.nan':                 0,            'is.finite':              0,
	'is.infinite':            0,            'is.vector':              0,
	'proc.time':              0,            'gc.time':                0,
	'withVisible':            1,            'expression':             1,
	'interactive':            0,            'invisible':              0,
	'rep':                    0,            'rep.int':                0,
	'rep_len':                0,            'seq.int':                0,
	'seq_len':                0,            'seq_along':              0,
	'list':                   1,            'xtfrm':                  0,
	'enc2native':             0,            'enc2utf8':               1,
	'emptyenv':               0,            'baseenv':                0,
	'globalenv':              0,            "'environment<-'":        0,
	"'pos.to.env'":           0,            "'.C'":                   0,
	"'.Fortran'":             1,            "'.External'":            0,
	"'.External2'":           1,            "'.Call'":                0,
	"'.External.graphics'":   0,            "'.Call.graphics'":       0,
	'eapply':                 0,            'lapply':                 0,
	'vapply':                 0,            'mapply':                 0,
	'Version':                0,            'machine':                0,
	'commandArgs':            0,            'internalsID':            0,
	'system':                 0,            'parse':                  0,
	'save':                   0,            'saveToConn':             0,
	'load':                   0,            'loadFromConn2':          0,
	'loadInfoFromConn2':      1,            'serializeToConn':        0,
	'unserializeFromConn':    0,            'serializeInfoFromConn':  1,
	'deparse':                0,            'dput':                   0,
	'dump':                   0,            'quit':                   0,
	'readline':               0,            'print.default':          0,
	'prmatrix':               0,            'gc':                     0,
	'gcinfo':                 0,            'gctorture':              0,
	'gctorture2':             0,            'memory.profile':         0,
	'mem.maxVSize':           0,            'mem.maxNSize':           0,
	'split':                  0,            'is.loaded':              0,
	'recordGraphics':         0,            'dyn.load':               0,
	'dyn.unload':             0,            'ls':                     1,
	'typeof':                 1,            'eval':                   0,
	'Exec':                   0,            'Tailcall':               1,
	'returnValue':            0,            'sys.parent':             1,
	'sys.call':               2,            'sys.frame':              3,
	'sys.nframe':             4,            'sys.calls':              5,
	'sys.frames':             6,            'sys.on.exit':            7,
	'sys.parents':            8,            'sys.function':           9,
	'traceback':              0,            'browserText':            1,
	'browserCondition':       2,            'browserSetDebug':        3,
	'parent.frame':           0,            'sort':                   1,
	'is.unsorted':            0,            'sorted_fpass':           0,
	'psort':                  0,            'qsort':                  0,
	'radixsort':              0,            'order':                  0,
	'rank':                   0,            'scan':                   0,
	't.default':              0,            'aperm':                  0,
	'builtins':               0,            'args':                   0,
	'formals':                0,            'body':                   0,
	'bodyCode':               0,            'environment':            0,
	'environmentName':        0,            'env2list':               0,
	'reg.finalizer':          0,            'options':                0,
	'getOption':              0,            'sink':                   0,
	'sink.number':            0,            'rapply':                 0,
	'islistfactor':           0,            'colSums':                0,
	'colMeans':               1,            'rowSums':                2,
	'rowMeans':               3,            'tracemem':               0,
	'retracemem':             0,            'untracemem':             0,
	'inspect':                0,            'address':                0,
	'named':                  0,            'refcnt':                 0,
	'merge':                  0,            'capabilities':           0,
	'capabilitiesX11':        0,            'new.env':                0,
	'parent.env':             0,            "'parent.env<-'":         0,
	'topenv':                 0,            'l10n_info':              0,
	'Cstack_info':            0,            'mmap_file':              0,
	'munmap_file':            0,            'wrap_meta':              0,
	'tryWrap':                0,            'altrep_class':           0,
	'file.show':              0,            'file.create':            0,
	'file.remove':            0,            'file.rename':            0,
	'file.append':            0,            'file.symlink':           0,
	'file.link':              0,            'file.copy':              0,
	'list.files':             0,            'list.dirs':              0,
	'file.exists':            0,            'file.choose':            0,
	'file.info':              0,            'file.access':            0,
	'dir.exists':             0,            'dir.create':             0,
	'tempfile':               0,            'tempdir':                0,
	'R.home':                 0,            'date':                   0,
	'Sys.getenv':             0,            'Sys.setenv':             0,
	'Sys.unsetenv':           0,            'getwd':                  0,
	'setwd':                  0,            'basename':               0,
	'dirname':                0,            'Sys.chmod':              0,
	'Sys.umask':              0,            'Sys.readlink':           0,
	'Sys.info':               0,            'Sys.sleep':              0,
	'Sys.getlocale':          0,            'Sys.setlocale':          0,
	'Sys.localeconv':         0,            'path.expand':            0,
	'Sys.getpid':             0,            'normalizePath':          0,
	'Sys.glob':               0,            'unlink':                 0,
	'polyroot':               0,            'inherits':               0,
	'UseMethod':              0,            'NextMethod':             0,
	'standardGeneric':        0,            'Sys.time':               0,
	'as.POSIXct':             0,            'as.POSIXlt':             0,
	'format.POSIXlt':         0,            'strptime':               0,
	'Date2POSIXlt':           0,            'POSIXlt2Date':           0,
	'balancePOSIXlt':         0,            'unCfillPOSIXlt':         1,
	'compareNumericVersion':  0,            'mkCode':                 0,
	'bcClose':                0,            "'is.builtin.internal'":  0,
	'disassemble':            0,            'bcVersion':              0,
	"'load.from.file'":       0,            "'save.to.file'":         0,
	'growconst':              0,            'putconst':               0,
	'getconst':               0,            'enableJIT':              0,
	'compilePKGS':            0,            'setNumMathThreads':      0,
	'setMaxNumMathThreads':   0,            'stdin':                  0,
	'stdout':                 0,            'stderr':                 0,
	'isatty':                 0,            'readLines':              0,
	'writeLines':             0,            'readBin':                0,
	'writeBin':               0,            'readChar':               0,
	'writeChar':              0,            'open':                   0,
	'isOpen':                 0,            'isIncomplete':           0,
	'isSeekable':             0,            'close':                  0,
	'flush':                  0,            'file':                   1,
	'url':                    0,            'pipe':                   0,
	'fifo':                   0,            'gzfile':                 0,
	'bzfile':                 1,            'xzfile':                 2,
	'zstdfile':               3,            'unz':                    0,
	'seek':                   0,            'truncate':               0,
	'pushBack':               0,            'clearPushBack':          0,
	'pushBackLength':         0,            'rawConnection':          0,
	'rawConnectionValue':     0,            'textConnection':         0,
	'textConnectionValue':    0,            'socketConnection':       0,
	'socketAccept':           1,            'sockSelect':             0,
	'serverSocket':           0,            'socketTimeout':          0,
	'getConnection':          0,            'getAllConnections':      0,
	'summary.connection':     0,            'gzcon':                  0,
	'memCompress':            0,            'memDecompress':          0,
	'readDCF':                0,            'lockEnvironment':        0,
	'environmentIsLocked':    0,            'lockBinding':            0,
	'unlockBinding':          1,            'bindingIsLocked':        0,
	'makeActiveBinding':      0,            'bindingIsActive':        0,
	'activeBindingFunction':  0,            'mkUnbound':              0,
	'isNamespaceEnv':         0,            'registerNamespace':      0,
	'unregisterNamespace':    0,            'getRegisteredNamespace': 0,
	'isRegisteredNamespace':  1,            'getNamespaceRegistry':   0,
	'importIntoEnv':          0,            'env.profile':            0,
	'Encoding':               0,            'setEncoding':            0,
	'setTimeLimit':           0,            'setSessionTimeLimit':    0,
	'icuSetCollate':          0,            'icuGetCollate':          0,
	'readRenviron':           0,            'shortRowNames':          0,
	'copyDFattr':             0,            'getRegisteredRoutines':  0,
	'getLoadedDLLs':          0,            'getSymbolInfo':          0,
	"'.isMethodsDispatchOn'": 0,            'lazyLoadDBfetch':        0,
	'lazyLoadDBflush':        0,            'getVarsFromFrame':       0,
	'lazyLoadDBinsertValue':  0,            'bincode':                0,
	'tabulate':               0,            'findInterval':           0,
	'pretty':                 0,            'formatC':                0,
	'crc64':                  0,            'bitwiseAnd':             1,
	'bitwiseNot':             2,            'bitwiseOr':              3,
	'bitwiseXor':             4,            'bitwiseShiftL':          5,
	'bitwiseShiftR':          6,            'serialize':              0,
	'serializeb':             1,            'unserialize':            2,
	'rowsum_matrix':          0,            'rowsum_df':              1,
	'setS4Object':            0,            'traceOnOff':             0,
	'debugOnOff':             1,            'La_qr_cmplx':            0,
	'La_rs':                  5,            'La_rs_cmplx':            51,
	'La_rg':                  3,            'La_rg_cmplx':            41,
	'La_dlange':              6,            'La_dgecon':              7,
	'La_dtrcon':              8,            'La_dtrcon3':             81,
	'La_zlange':              61,           'La_zgecon':              9,
	'La_ztrcon':              10,           'La_ztrcon3':             13,
	'La_solve_cmplx':         11,           'La_solve':               100,
	'La_qr':                  101,          'La_chol':                200,
	'La_chol2inv':            201,          'qr_coef_real':           300,
	'qr_qy_real':             301,          'det_ge_real':            302,
	'qr_coef_cmplx':          303,          'qr_qy_cmplx':            304,
	'La_svd':                 400,          'La_svd_cmplx':           401,
	'La_version':             1000,         'La_library':             1001,
	'bcprofcounts':           0,            'bcprofstart':            0,
	'bcprofstop':             0,            'eSoftVersion':           0,
	'curlVersion':            0,            'curlGetHeaders':         0,
	'curlDownload':           0,            'compilerVersion':        0,
} as const;