export enum TreeSitterType {
    Program = 'program',
    BracedExpression = 'braced_expression',
    ParenthesizedExpression = 'parenthesized_expression',
    BinaryOperator = 'binary_operator',
    UnaryOperator = 'unary_operator',
    Identifier = 'identifier',
    IfStatement = 'if_statement',
    ForStatement = 'for_statement',
    WhileStatement = 'while_statement',
    RepeatStatement = 'repeat_statement',
    Float = 'float',
    True = 'true',
    False = 'false',
    Break = 'break',
    Next = 'next',
    Subset = 'subset',
    Subset2 = 'subset2',
    ExtractOperator = 'extract_operator',
    NamespaceOperator = 'namespace',
    Argument = 'argument',
    Comment = 'comment'
}
